/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import * as models from "../index.js";
import { SfcError } from "./sfc-error.js";

export type MarketApiInternalServerErrorData = {
  error: models.MarketApiInternalServerErrorError;
};

export class MarketApiInternalServerError extends SfcError {
  error: models.MarketApiInternalServerErrorError;

  /** The original data that was passed to this error instance. */
  data$: MarketApiInternalServerErrorData;

  constructor(
    err: MarketApiInternalServerErrorData,
    httpMeta: { response: Response; request: Request; body: string },
  ) {
    const message = err.error?.message
      || `API error occurred: ${JSON.stringify(err)}`;
    super(message, httpMeta);
    this.data$ = err;
    this.error = err.error;

    this.name = "MarketApiInternalServerError";
  }
}

/** @internal */
export const MarketApiInternalServerError$inboundSchema: z.ZodMiniType<
  MarketApiInternalServerError,
  unknown
> = z.pipe(
  z.object({
    error: z.lazy(() => models.MarketApiInternalServerErrorError$inboundSchema),
    request$: z.custom<Request>(x => x instanceof Request),
    response$: z.custom<Response>(x => x instanceof Response),
    body$: z.string(),
  }),
  z.transform((v) => {
    return new MarketApiInternalServerError(v, {
      request: v.request$,
      response: v.response$,
      body: v.body$,
    });
  }),
);
