/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import * as models from "../index.js";
import { SfcError } from "./sfc-error.js";

export type MarketApiPaymentRequiredErrorData = {
  error: models.MarketApiPaymentRequiredErrorError;
};

export class MarketApiPaymentRequiredError extends SfcError {
  error: models.MarketApiPaymentRequiredErrorError;

  /** The original data that was passed to this error instance. */
  data$: MarketApiPaymentRequiredErrorData;

  constructor(
    err: MarketApiPaymentRequiredErrorData,
    httpMeta: { response: Response; request: Request; body: string },
  ) {
    const message = err.error?.message
      || `API error occurred: ${JSON.stringify(err)}`;
    super(message, httpMeta);
    this.data$ = err;
    this.error = err.error;

    this.name = "MarketApiPaymentRequiredError";
  }
}

/** @internal */
export const MarketApiPaymentRequiredError$inboundSchema: z.ZodMiniType<
  MarketApiPaymentRequiredError,
  unknown
> = z.pipe(
  z.object({
    error: z.lazy(() =>
      models.MarketApiPaymentRequiredErrorError$inboundSchema
    ),
    request$: z.custom<Request>(x => x instanceof Request),
    response$: z.custom<Response>(x => x instanceof Response),
    body$: z.string(),
  }),
  z.transform((v) => {
    return new MarketApiPaymentRequiredError(v, {
      request: v.request$,
      response: v.response$,
      body: v.body$,
    });
  }),
);
