/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { SfcCore } from "../core.js";
import { encodeFormQuery, encodeSimple } from "../lib/encodings.js";
import * as M from "../lib/matchers.js";
import { compactMap } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import { RequestOptions } from "../lib/sdks.js";
import { resolveSecurity } from "../lib/security.js";
import { pathToFunc } from "../lib/url.js";
import {
  ConnectionError,
  InvalidRequestError,
  RequestAbortedError,
  RequestTimeoutError,
  UnexpectedClientError,
} from "../models/errors/http-client-errors.js";
import * as errors from "../models/errors/index.js";
import { ResponseValidationError } from "../models/errors/response-validation-error.js";
import { SDKValidationError } from "../models/errors/sdk-validation-error.js";
import { SfcError } from "../models/errors/sfc-error.js";
import * as models from "../models/index.js";
import * as operations from "../models/operations/index.js";
import { APICall, APIPromise } from "../types/async.js";
import { Result } from "../types/fp.js";

/**
 * Get node logs
 *
 * @remarks
 * Retrieve logs for a node.
 */
export function nodesGetLogs(
  client: SfcCore,
  security: operations.GetNodeLogsSecurity,
  request: operations.GetNodeLogsRequest,
  options?: RequestOptions,
): APIPromise<
  Result<
    models.VmorchNodeLogsResponse,
    | errors.VmorchUnauthorizedError
    | errors.VmorchNotFoundError
    | errors.VmorchUnprocessableEntityError
    | errors.VmorchInternalServerError
    | SfcError
    | ResponseValidationError
    | ConnectionError
    | RequestAbortedError
    | RequestTimeoutError
    | InvalidRequestError
    | UnexpectedClientError
    | SDKValidationError
  >
> {
  return new APIPromise($do(
    client,
    security,
    request,
    options,
  ));
}

async function $do(
  client: SfcCore,
  security: operations.GetNodeLogsSecurity,
  request: operations.GetNodeLogsRequest,
  options?: RequestOptions,
): Promise<
  [
    Result<
      models.VmorchNodeLogsResponse,
      | errors.VmorchUnauthorizedError
      | errors.VmorchNotFoundError
      | errors.VmorchUnprocessableEntityError
      | errors.VmorchInternalServerError
      | SfcError
      | ResponseValidationError
      | ConnectionError
      | RequestAbortedError
      | RequestTimeoutError
      | InvalidRequestError
      | UnexpectedClientError
      | SDKValidationError
    >,
    APICall,
  ]
> {
  const parsed = safeParse(
    request,
    (value) => z.parse(operations.GetNodeLogsRequest$outboundSchema, value),
    "Input validation failed",
  );
  if (!parsed.ok) {
    return [parsed, { status: "invalid" }];
  }
  const payload = parsed.value;
  const body = null;

  const pathParams = {
    id: encodeSimple("id", payload.id, {
      explode: false,
      charEncoding: "percent",
    }),
  };

  const path = pathToFunc("/v2/nodes/{id}/logs")(pathParams);

  const query = encodeFormQuery({
    "limit": payload.limit,
    "realtime_timestamp_after": payload.realtime_timestamp_after,
    "realtime_timestamp_before": payload.realtime_timestamp_before,
    "seqnum_after": payload.seqnum_after,
    "seqnum_before": payload.seqnum_before,
    "sort_by": payload.sort_by,
  });

  const headers = new Headers(compactMap({
    Accept: "application/json",
  }));

  const requestSecurity = resolveSecurity(
    [
      {
        fieldName: "Authorization",
        type: "http:bearer",
        value: security?.vmorchBearerAuth,
      },
    ],
  );

  const context = {
    options: client._options,
    baseURL: options?.serverURL ?? client._baseURL ?? "",
    operationID: "get_node_logs",
    oAuth2Scopes: null,

    resolvedSecurity: requestSecurity,

    securitySource: security,
    retryConfig: options?.retries
      || client._options.retryConfig
      || { strategy: "none" },
    retryCodes: options?.retryCodes || ["429", "500", "502", "503", "504"],
  };

  const requestRes = client._createRequest(context, {
    security: requestSecurity,
    method: "GET",
    baseURL: options?.serverURL,
    path: path,
    headers: headers,
    query: query,
    body: body,
    userAgent: client._options.userAgent,
    timeoutMs: options?.timeoutMs || client._options.timeoutMs || -1,
  }, options);
  if (!requestRes.ok) {
    return [requestRes, { status: "invalid" }];
  }
  const req = requestRes.value;

  const doResult = await client._do(req, {
    context,
    errorCodes: ["401", "404", "422", "4XX", "500", "5XX"],
    retryConfig: context.retryConfig,
    retryCodes: context.retryCodes,
  });
  if (!doResult.ok) {
    return [doResult, { status: "request-error", request: req }];
  }
  const response = doResult.value;

  const responseFields = {
    HttpMeta: { Response: response, Request: req },
  };

  const [result] = await M.match<
    models.VmorchNodeLogsResponse,
    | errors.VmorchUnauthorizedError
    | errors.VmorchNotFoundError
    | errors.VmorchUnprocessableEntityError
    | errors.VmorchInternalServerError
    | SfcError
    | ResponseValidationError
    | ConnectionError
    | RequestAbortedError
    | RequestTimeoutError
    | InvalidRequestError
    | UnexpectedClientError
    | SDKValidationError
  >(
    M.json(200, models.VmorchNodeLogsResponse$inboundSchema),
    M.jsonErr(401, errors.VmorchUnauthorizedError$inboundSchema),
    M.jsonErr(404, errors.VmorchNotFoundError$inboundSchema),
    M.jsonErr(422, errors.VmorchUnprocessableEntityError$inboundSchema),
    M.jsonErr(500, errors.VmorchInternalServerError$inboundSchema),
    M.fail("4XX"),
    M.fail("5XX"),
  )(response, req, { extraFields: responseFields });
  if (!result.ok) {
    return [result, { status: "complete", request: req, response }];
  }

  return [result, { status: "complete", request: req, response }];
}
