/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { capacitiesCreate } from "../funcs/capacities-create.js";
import { capacitiesDelete } from "../funcs/capacities-delete.js";
import { capacitiesFetch } from "../funcs/capacities-fetch.js";
import { capacitiesList } from "../funcs/capacities-list.js";
import { capacitiesUpdate } from "../funcs/capacities-update.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as models from "../models/index.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";
import { PageIterator, unwrapResultIterator } from "../types/operations.js";

export class Capacities extends ClientSDK {
  /**
   * List capacities
   *
   * @remarks
   * List all capacities.
   */
  async list(
    request?: operations.ListCapacitiesRequest | undefined,
    options?: RequestOptions,
  ): Promise<
    PageIterator<operations.ListCapacitiesResponse, { cursor: string }>
  > {
    return unwrapResultIterator(capacitiesList(
      this,
      request,
      options,
    ));
  }

  /**
   * Create capacity
   *
   * @remarks
   * Create a capacity to hold compute in specified zones.
   */
  async create(
    request: models.CreateCapacityRequest,
    options?: RequestOptions,
  ): Promise<models.CapacityResponse> {
    return unwrapAsync(capacitiesCreate(
      this,
      request,
      options,
    ));
  }

  /**
   * Get capacity
   *
   * @remarks
   * Retrieve a capacity by ID or name, including its compute schedule and scheduler configuration.
   */
  async fetch(
    request: operations.FetchCapacityRequest,
    options?: RequestOptions,
  ): Promise<models.CapacityResponse> {
    return unwrapAsync(capacitiesFetch(
      this,
      request,
      options,
    ));
  }

  /**
   * Delete capacity
   *
   * @remarks
   * Delete a capacity. The capacity must be empty and the scheduler must be disabled or absent.
   */
  async delete(
    request: operations.DeleteCapacityRequest,
    options?: RequestOptions,
  ): Promise<void> {
    return unwrapAsync(capacitiesDelete(
      this,
      request,
      options,
    ));
  }

  /**
   * Update capacity
   *
   * @remarks
   * Update a capacity. Omitted fields are left unchanged.
   */
  async update(
    request: operations.UpdateCapacityRequest,
    options?: RequestOptions,
  ): Promise<models.CapacityResponse> {
    return unwrapAsync(capacitiesUpdate(
      this,
      request,
      options,
    ));
  }
}
