/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { imagesCompleteUpload } from "../funcs/images-complete-upload.js";
import { imagesDownload } from "../funcs/images-download.js";
import { imagesGet } from "../funcs/images-get.js";
import { imagesList } from "../funcs/images-list.js";
import { imagesStartUpload } from "../funcs/images-start-upload.js";
import { imagesUploadPart } from "../funcs/images-upload-part.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as models from "../models/index.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";

export class Images extends ClientSDK {
  /**
   * List images
   *
   * @remarks
   * List all machine images.
   */
  async list(
    security: operations.ListImagesV2Security,
    request?: operations.ListImagesV2Request | undefined,
    options?: RequestOptions,
  ): Promise<models.VmorchListImagesResponse> {
    return unwrapAsync(imagesList(
      this,
      security,
      request,
      options,
    ));
  }

  /**
   * Create image
   *
   * @remarks
   * Create an image and start a multipart upload.
   */
  async startUpload(
    security: operations.StartUploadSecurity,
    request: models.VmorchStartUploadRequest,
    options?: RequestOptions,
  ): Promise<models.VmorchImageResponse> {
    return unwrapAsync(imagesStartUpload(
      this,
      security,
      request,
      options,
    ));
  }

  /**
   * Get image
   *
   * @remarks
   * Retrieve an image by ID.
   */
  async get(
    security: operations.GetImageSecurity,
    request: operations.GetImageRequest,
    options?: RequestOptions,
  ): Promise<models.VmorchImageResponse> {
    return unwrapAsync(imagesGet(
      this,
      security,
      request,
      options,
    ));
  }

  /**
   * Complete image upload
   *
   * @remarks
   * Complete a multipart image upload after all parts have been uploaded.
   */
  async completeUpload(
    security: operations.CompleteUploadSecurity,
    request: operations.CompleteUploadRequest,
    options?: RequestOptions,
  ): Promise<models.VmorchImageResponse> {
    return unwrapAsync(imagesCompleteUpload(
      this,
      security,
      request,
      options,
    ));
  }

  /**
   * Download image
   *
   * @remarks
   * Get a presigned URL to download an image.
   */
  async download(
    security: operations.DownloadImageV2Security,
    request: operations.DownloadImageV2Request,
    options?: RequestOptions,
  ): Promise<models.VmorchImageDownloadResponse> {
    return unwrapAsync(imagesDownload(
      this,
      security,
      request,
      options,
    ));
  }

  /**
   * Create image upload part URL
   *
   * @remarks
   * Get a presigned URL to upload a part of a multipart image upload.
   */
  async uploadPart(
    security: operations.UploadPartSecurity,
    request: operations.UploadPartRequest,
    options?: RequestOptions,
  ): Promise<models.VmorchUploadPartResponse> {
    return unwrapAsync(imagesUploadPart(
      this,
      security,
      request,
      options,
    ));
  }
}
