/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { imagesCompleteUpload } from "../funcs/images-complete-upload.js";
import { imagesDelete } from "../funcs/images-delete.js";
import { imagesDownload } from "../funcs/images-download.js";
import { imagesFetch } from "../funcs/images-fetch.js";
import { imagesList } from "../funcs/images-list.js";
import { imagesStartUpload } from "../funcs/images-start-upload.js";
import { imagesUploadPart } from "../funcs/images-upload-part.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as models from "../models/index.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";
import { PageIterator, unwrapResultIterator } from "../types/operations.js";

export class Images extends ClientSDK {
  /**
   * List images
   *
   * @remarks
   * List all images owned by the authenticated user.
   */
  async list(
    request?: operations.ListImagesRequest | undefined,
    options?: RequestOptions,
  ): Promise<PageIterator<operations.ListImagesResponse, { cursor: string }>> {
    return unwrapResultIterator(imagesList(
      this,
      request,
      options,
    ));
  }

  /**
   * Create image
   *
   * @remarks
   * Create an image and start a multipart upload.
   */
  async startUpload(
    request: models.StartUploadRequest,
    options?: RequestOptions,
  ): Promise<models.ImageUploadResponse> {
    return unwrapAsync(imagesStartUpload(
      this,
      request,
      options,
    ));
  }

  /**
   * Get image
   *
   * @remarks
   * Retrieve an image by ID. Returns both user-owned and public images.
   */
  async fetch(
    request: operations.FetchImageRequest,
    options?: RequestOptions,
  ): Promise<models.ImageListEntry> {
    return unwrapAsync(imagesFetch(
      this,
      request,
      options,
    ));
  }

  /**
   * Delete image
   *
   * @remarks
   * Delete an image. This is a soft delete.
   */
  async delete(
    request: operations.DeleteImageRequest,
    options?: RequestOptions,
  ): Promise<models.DeleteImageResponse> {
    return unwrapAsync(imagesDelete(
      this,
      request,
      options,
    ));
  }

  /**
   * Complete image upload
   *
   * @remarks
   * Complete a multipart image upload after all parts have been uploaded.
   */
  async completeUpload(
    request: operations.CompleteImageUploadRequest,
    options?: RequestOptions,
  ): Promise<models.ImageUploadResponse> {
    return unwrapAsync(imagesCompleteUpload(
      this,
      request,
      options,
    ));
  }

  /**
   * Download image
   *
   * @remarks
   * Get a presigned URL to download an image. Works for both user-owned and public images.
   */
  async download(
    request: operations.DownloadImageRequest,
    options?: RequestOptions,
  ): Promise<models.ImageDownloadResponse> {
    return unwrapAsync(imagesDownload(
      this,
      request,
      options,
    ));
  }

  /**
   * Create image upload part URL
   *
   * @remarks
   * Get a presigned URL to upload a part of a multipart image upload.
   */
  async uploadPart(
    request: operations.CreateImageUploadPartUrlRequest,
    options?: RequestOptions,
  ): Promise<models.UploadPartResponse> {
    return unwrapAsync(imagesUploadPart(
      this,
      request,
      options,
    ));
  }
}
