/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { nodeTemplatesCreate } from "../funcs/node-templates-create.js";
import { nodeTemplatesDelete } from "../funcs/node-templates-delete.js";
import { nodeTemplatesGet } from "../funcs/node-templates-get.js";
import { nodeTemplatesList } from "../funcs/node-templates-list.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as models from "../models/index.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";

export class NodeTemplates extends ClientSDK {
  /**
   * List node templates
   *
   * @remarks
   * List all node templates.
   */
  async list(
    request?: operations.ListNodeTemplatesHandlerRequest | undefined,
    options?: RequestOptions,
  ): Promise<models.MarketApiListNodeTemplatesResponse> {
    return unwrapAsync(nodeTemplatesList(
      this,
      request,
      options,
    ));
  }

  /**
   * Create node template
   *
   * @remarks
   * Create a reusable node configuration.
   */
  async create(
    request: models.MarketApiCreateNodeTemplateRequest,
    options?: RequestOptions,
  ): Promise<models.MarketApiNodeTemplateResponse> {
    return unwrapAsync(nodeTemplatesCreate(
      this,
      request,
      options,
    ));
  }

  /**
   * Get node template
   *
   * @remarks
   * Retrieve a node template by ID or name.
   */
  async get(
    request: operations.GetNodeTemplateHandlerRequest,
    options?: RequestOptions,
  ): Promise<models.MarketApiNodeTemplateResponse> {
    return unwrapAsync(nodeTemplatesGet(
      this,
      request,
      options,
    ));
  }

  /**
   * Delete node template
   *
   * @remarks
   * Delete a node template. The template must not be in use by any capacity.
   */
  async delete(
    request: operations.DeleteNodeTemplateHandlerRequest,
    options?: RequestOptions,
  ): Promise<void> {
    return unwrapAsync(nodeTemplatesDelete(
      this,
      request,
      options,
    ));
  }
}
