/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { nodesFetch } from "../funcs/nodes-fetch.js";
import { nodesGetLogsForNode } from "../funcs/nodes-get-logs-for-node.js";
import { nodesGetSSHInfoForNode } from "../funcs/nodes-get-ssh-info-for-node.js";
import { nodesList } from "../funcs/nodes-list.js";
import { nodesReplace } from "../funcs/nodes-replace.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as models from "../models/index.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";

export class Nodes extends ClientSDK {
  /**
   * List nodes
   *
   * @remarks
   * List all nodes.
   */
  async list(
    request?: operations.ListNodesRequest | undefined,
    options?: RequestOptions,
  ): Promise<models.ListNodesResponse> {
    return unwrapAsync(nodesList(
      this,
      request,
      options,
    ));
  }

  /**
   * Get node
   *
   * @remarks
   * Retrieve a node by ID.
   */
  async fetch(
    request: operations.FetchNodeRequest,
    options?: RequestOptions,
  ): Promise<models.NodeResponse> {
    return unwrapAsync(nodesFetch(
      this,
      request,
      options,
    ));
  }

  /**
   * Get node logs
   *
   * @remarks
   * Retrieve logs for a node.
   */
  async getLogsForNode(
    request: operations.GetNodeLogsRequest,
    options?: RequestOptions,
  ): Promise<models.NodeLogsResponse> {
    return unwrapAsync(nodesGetLogsForNode(
      this,
      request,
      options,
    ));
  }

  /**
   * Replace node
   *
   * @remarks
   * Replace a node by destroying it and creating a new one in the same capacity.
   */
  async replace(
    request: operations.ReplaceNodeRequest,
    options?: RequestOptions,
  ): Promise<models.NodeResponse> {
    return unwrapAsync(nodesReplace(
      this,
      request,
      options,
    ));
  }

  /**
   * Get node SSH info
   *
   * @remarks
   * Retrieve SSH connection details for a node.
   */
  async getSSHInfoForNode(
    request: operations.GetNodeSshRequest,
    options?: RequestOptions,
  ): Promise<models.NodeSshInfo> {
    return unwrapAsync(nodesGetSSHInfoForNode(
      this,
      request,
      options,
    ));
  }
}
