/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { ordersCancel } from "../funcs/orders-cancel.js";
import { ordersCreate } from "../funcs/orders-create.js";
import { ordersFetch } from "../funcs/orders-fetch.js";
import { ordersList } from "../funcs/orders-list.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as models from "../models/index.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";
import { PageIterator, unwrapResultIterator } from "../types/operations.js";

export class Orders extends ClientSDK {
  /**
   * List orders
   *
   * @remarks
   * List all orders.
   */
  async list(
    request?: operations.ListOrdersRequest | undefined,
    options?: RequestOptions,
  ): Promise<PageIterator<operations.ListOrdersResponse, { cursor: string }>> {
    return unwrapResultIterator(ordersList(
      this,
      request,
      options,
    ));
  }

  /**
   * Create order
   *
   * @remarks
   * Place a buy or sell order. Orders fill completely or not at all. All nodes fill in a single zone. Order filling is asynchronous; poll `GET /v2/orders/{id}` to check status.
   */
  async create(
    request: operations.CreateOrderRequest,
    options?: RequestOptions,
  ): Promise<models.V2OrderResponse> {
    return unwrapAsync(ordersCreate(
      this,
      request,
      options,
    ));
  }

  /**
   * Get order
   *
   * @remarks
   * Retrieve an order by ID.
   */
  async fetch(
    request: operations.FetchOrderRequest,
    options?: RequestOptions,
  ): Promise<models.V2OrderResponse> {
    return unwrapAsync(ordersFetch(
      this,
      request,
      options,
    ));
  }

  /**
   * Cancel order
   *
   * @remarks
   * Request cancellation of an order. This is asynchronous — poll `GET /v2/orders/{id}` to confirm the status has changed to cancelled.
   */
  async cancel(
    request: operations.CancelOrderRequest,
    options?: RequestOptions,
  ): Promise<void> {
    return unwrapAsync(ordersCancel(
      this,
      request,
      options,
    ));
  }
}
