/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { ClientSDK } from "../lib/sdks.js";
import { Capacities } from "./capacities.js";
import { Images } from "./images.js";
import { NodeTemplates } from "./node-templates.js";
import { Nodes } from "./nodes.js";
import { Orders } from "./orders.js";

export class Sfc extends ClientSDK {
  private _capacities?: Capacities;
  get capacities(): Capacities {
    return (this._capacities ??= new Capacities(this._options));
  }

  private _images?: Images;
  get images(): Images {
    return (this._images ??= new Images(this._options));
  }

  private _nodeTemplates?: NodeTemplates;
  get nodeTemplates(): NodeTemplates {
    return (this._nodeTemplates ??= new NodeTemplates(this._options));
  }

  private _nodes?: Nodes;
  get nodes(): Nodes {
    return (this._nodes ??= new Nodes(this._options));
  }

  private _orders?: Orders;
  get orders(): Orders {
    return (this._orders ??= new Orders(this._options));
  }
}
