/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import dotenv from "dotenv";
dotenv.config();
/**
 * Example usage of the @sfcompute/sdk SDK
 *
 * To run this example from the examples directory:
 * npm run build && npx tsx capacitiesList.example.ts
 */

import { Sfc } from "@sfcompute/sdk";

const sfc = new Sfc({
  serverURL: "https://api.example.com",
  marketApiBearerAuth: process.env["SFC_MARKET_API_BEARER_AUTH"] ?? "",
});

async function main() {
  const result = await sfc.capacities.list({
    startingAfter: "capc_gqXR7s0Kj5mHvE2wNpLc4Q",
    endingBefore: "capc_gqXR7s0Kj5mHvE2wNpLc4Q",
  });

  console.log(result);
}

main().catch(console.error);
