/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";

export type CancelOrderRequest = {
  /**
   * Order ID
   */
  id: string;
};

/** @internal */
export type CancelOrderRequest$Outbound = {
  id: string;
};

/** @internal */
export const CancelOrderRequest$outboundSchema: z.ZodMiniType<
  CancelOrderRequest$Outbound,
  CancelOrderRequest
> = z.object({
  id: z.string(),
});

export function cancelOrderRequestToJSON(
  cancelOrderRequest: CancelOrderRequest,
): string {
  return JSON.stringify(
    CancelOrderRequest$outboundSchema.parse(cancelOrderRequest),
  );
}
