/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import * as models from "../index.js";

export type CompleteUploadSecurity = {
  vmorchBearerAuth: string;
};

export type CompleteUploadRequest = {
  id: string;
  body: models.VmorchCompleteUploadRequest;
};

/** @internal */
export type CompleteUploadSecurity$Outbound = {
  vmorch_bearer_auth: string;
};

/** @internal */
export const CompleteUploadSecurity$outboundSchema: z.ZodMiniType<
  CompleteUploadSecurity$Outbound,
  CompleteUploadSecurity
> = z.pipe(
  z.object({
    vmorchBearerAuth: z.string(),
  }),
  z.transform((v) => {
    return remap$(v, {
      vmorchBearerAuth: "vmorch_bearer_auth",
    });
  }),
);

export function completeUploadSecurityToJSON(
  completeUploadSecurity: CompleteUploadSecurity,
): string {
  return JSON.stringify(
    CompleteUploadSecurity$outboundSchema.parse(completeUploadSecurity),
  );
}

/** @internal */
export type CompleteUploadRequest$Outbound = {
  id: string;
  body: models.VmorchCompleteUploadRequest$Outbound;
};

/** @internal */
export const CompleteUploadRequest$outboundSchema: z.ZodMiniType<
  CompleteUploadRequest$Outbound,
  CompleteUploadRequest
> = z.object({
  id: z.string(),
  body: models.VmorchCompleteUploadRequest$outboundSchema,
});

export function completeUploadRequestToJSON(
  completeUploadRequest: CompleteUploadRequest,
): string {
  return JSON.stringify(
    CompleteUploadRequest$outboundSchema.parse(completeUploadRequest),
  );
}
