/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import * as models from "../index.js";

export type CompleteImageUploadRequest = {
  /**
   * Image ID
   */
  id: string;
  body: models.CompleteUploadRequest;
};

/** @internal */
export type CompleteImageUploadRequest$Outbound = {
  id: string;
  body: models.CompleteUploadRequest$Outbound;
};

/** @internal */
export const CompleteImageUploadRequest$outboundSchema: z.ZodMiniType<
  CompleteImageUploadRequest$Outbound,
  CompleteImageUploadRequest
> = z.object({
  id: z.string(),
  body: models.CompleteUploadRequest$outboundSchema,
});

export function completeImageUploadRequestToJSON(
  completeImageUploadRequest: CompleteImageUploadRequest,
): string {
  return JSON.stringify(
    CompleteImageUploadRequest$outboundSchema.parse(completeImageUploadRequest),
  );
}
