/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import * as models from "../index.js";

export type CreateImageUploadPartUrlRequest = {
  /**
   * Image ID
   */
  id: string;
  body: models.UploadPartRequest;
};

/** @internal */
export type CreateImageUploadPartUrlRequest$Outbound = {
  id: string;
  body: models.UploadPartRequest$Outbound;
};

/** @internal */
export const CreateImageUploadPartUrlRequest$outboundSchema: z.ZodMiniType<
  CreateImageUploadPartUrlRequest$Outbound,
  CreateImageUploadPartUrlRequest
> = z.object({
  id: z.string(),
  body: models.UploadPartRequest$outboundSchema,
});

export function createImageUploadPartUrlRequestToJSON(
  createImageUploadPartUrlRequest: CreateImageUploadPartUrlRequest,
): string {
  return JSON.stringify(
    CreateImageUploadPartUrlRequest$outboundSchema.parse(
      createImageUploadPartUrlRequest,
    ),
  );
}
