/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import * as models from "../index.js";

export type CreateOrderRequest = {
  /**
   * Unique key to ensure idempotent order creation. If provided, duplicate requests with the same key will not place a new order and return the original order.
   */
  idempotencyKey?: string | null | undefined;
  body: models.V2CreateOrderRequest;
};

/** @internal */
export type CreateOrderRequest$Outbound = {
  "Idempotency-Key"?: string | null | undefined;
  body: models.V2CreateOrderRequest$Outbound;
};

/** @internal */
export const CreateOrderRequest$outboundSchema: z.ZodMiniType<
  CreateOrderRequest$Outbound,
  CreateOrderRequest
> = z.pipe(
  z.object({
    idempotencyKey: z.optional(z.nullable(z.string())),
    body: models.V2CreateOrderRequest$outboundSchema,
  }),
  z.transform((v) => {
    return remap$(v, {
      idempotencyKey: "Idempotency-Key",
    });
  }),
);

export function createOrderRequestToJSON(
  createOrderRequest: CreateOrderRequest,
): string {
  return JSON.stringify(
    CreateOrderRequest$outboundSchema.parse(createOrderRequest),
  );
}
