/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";

export type DeleteCapacityRequest = {
  id: string;
};

/** @internal */
export type DeleteCapacityRequest$Outbound = {
  id: string;
};

/** @internal */
export const DeleteCapacityRequest$outboundSchema: z.ZodMiniType<
  DeleteCapacityRequest$Outbound,
  DeleteCapacityRequest
> = z.object({
  id: z.string(),
});

export function deleteCapacityRequestToJSON(
  deleteCapacityRequest: DeleteCapacityRequest,
): string {
  return JSON.stringify(
    DeleteCapacityRequest$outboundSchema.parse(deleteCapacityRequest),
  );
}
