/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";

export type DeleteNodeTemplateHandlerRequest = {
  id: string;
};

/** @internal */
export type DeleteNodeTemplateHandlerRequest$Outbound = {
  id: string;
};

/** @internal */
export const DeleteNodeTemplateHandlerRequest$outboundSchema: z.ZodMiniType<
  DeleteNodeTemplateHandlerRequest$Outbound,
  DeleteNodeTemplateHandlerRequest
> = z.object({
  id: z.string(),
});

export function deleteNodeTemplateHandlerRequestToJSON(
  deleteNodeTemplateHandlerRequest: DeleteNodeTemplateHandlerRequest,
): string {
  return JSON.stringify(
    DeleteNodeTemplateHandlerRequest$outboundSchema.parse(
      deleteNodeTemplateHandlerRequest,
    ),
  );
}
