/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";

export type DeleteImageRequest = {
  /**
   * Image ID
   */
  id: string;
};

/** @internal */
export type DeleteImageRequest$Outbound = {
  id: string;
};

/** @internal */
export const DeleteImageRequest$outboundSchema: z.ZodMiniType<
  DeleteImageRequest$Outbound,
  DeleteImageRequest
> = z.object({
  id: z.string(),
});

export function deleteImageRequestToJSON(
  deleteImageRequest: DeleteImageRequest,
): string {
  return JSON.stringify(
    DeleteImageRequest$outboundSchema.parse(deleteImageRequest),
  );
}
