/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";

export type DeleteCapacityHandlerRequest = {
  id: string;
};

/** @internal */
export type DeleteCapacityHandlerRequest$Outbound = {
  id: string;
};

/** @internal */
export const DeleteCapacityHandlerRequest$outboundSchema: z.ZodMiniType<
  DeleteCapacityHandlerRequest$Outbound,
  DeleteCapacityHandlerRequest
> = z.object({
  id: z.string(),
});

export function deleteCapacityHandlerRequestToJSON(
  deleteCapacityHandlerRequest: DeleteCapacityHandlerRequest,
): string {
  return JSON.stringify(
    DeleteCapacityHandlerRequest$outboundSchema.parse(
      deleteCapacityHandlerRequest,
    ),
  );
}
