/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";

export type DeleteNodeTemplateRequest = {
  id: string;
};

/** @internal */
export type DeleteNodeTemplateRequest$Outbound = {
  id: string;
};

/** @internal */
export const DeleteNodeTemplateRequest$outboundSchema: z.ZodMiniType<
  DeleteNodeTemplateRequest$Outbound,
  DeleteNodeTemplateRequest
> = z.object({
  id: z.string(),
});

export function deleteNodeTemplateRequestToJSON(
  deleteNodeTemplateRequest: DeleteNodeTemplateRequest,
): string {
  return JSON.stringify(
    DeleteNodeTemplateRequest$outboundSchema.parse(deleteNodeTemplateRequest),
  );
}
