/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";

export type DownloadImageV2Security = {
  vmorchBearerAuth: string;
};

export type DownloadImageV2Request = {
  id: string;
};

/** @internal */
export type DownloadImageV2Security$Outbound = {
  vmorch_bearer_auth: string;
};

/** @internal */
export const DownloadImageV2Security$outboundSchema: z.ZodMiniType<
  DownloadImageV2Security$Outbound,
  DownloadImageV2Security
> = z.pipe(
  z.object({
    vmorchBearerAuth: z.string(),
  }),
  z.transform((v) => {
    return remap$(v, {
      vmorchBearerAuth: "vmorch_bearer_auth",
    });
  }),
);

export function downloadImageV2SecurityToJSON(
  downloadImageV2Security: DownloadImageV2Security,
): string {
  return JSON.stringify(
    DownloadImageV2Security$outboundSchema.parse(downloadImageV2Security),
  );
}

/** @internal */
export type DownloadImageV2Request$Outbound = {
  id: string;
};

/** @internal */
export const DownloadImageV2Request$outboundSchema: z.ZodMiniType<
  DownloadImageV2Request$Outbound,
  DownloadImageV2Request
> = z.object({
  id: z.string(),
});

export function downloadImageV2RequestToJSON(
  downloadImageV2Request: DownloadImageV2Request,
): string {
  return JSON.stringify(
    DownloadImageV2Request$outboundSchema.parse(downloadImageV2Request),
  );
}
