/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";

export type DownloadImageRequest = {
  /**
   * Image ID
   */
  id: string;
};

/** @internal */
export type DownloadImageRequest$Outbound = {
  id: string;
};

/** @internal */
export const DownloadImageRequest$outboundSchema: z.ZodMiniType<
  DownloadImageRequest$Outbound,
  DownloadImageRequest
> = z.object({
  id: z.string(),
});

export function downloadImageRequestToJSON(
  downloadImageRequest: DownloadImageRequest,
): string {
  return JSON.stringify(
    DownloadImageRequest$outboundSchema.parse(downloadImageRequest),
  );
}
