/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";

export type FetchNodeSshRequest = {
  id: string;
};

/** @internal */
export type FetchNodeSshRequest$Outbound = {
  id: string;
};

/** @internal */
export const FetchNodeSshRequest$outboundSchema: z.ZodMiniType<
  FetchNodeSshRequest$Outbound,
  FetchNodeSshRequest
> = z.object({
  id: z.string(),
});

export function fetchNodeSshRequestToJSON(
  fetchNodeSshRequest: FetchNodeSshRequest,
): string {
  return JSON.stringify(
    FetchNodeSshRequest$outboundSchema.parse(fetchNodeSshRequest),
  );
}
