/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";

export type FetchImageRequest = {
  /**
   * Image ID
   */
  id: string;
};

/** @internal */
export type FetchImageRequest$Outbound = {
  id: string;
};

/** @internal */
export const FetchImageRequest$outboundSchema: z.ZodMiniType<
  FetchImageRequest$Outbound,
  FetchImageRequest
> = z.object({
  id: z.string(),
});

export function fetchImageRequestToJSON(
  fetchImageRequest: FetchImageRequest,
): string {
  return JSON.stringify(
    FetchImageRequest$outboundSchema.parse(fetchImageRequest),
  );
}
