/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import { ClosedEnum } from "../../types/enums.js";

export const FetchNodeLogsSortBy = {
  Seqnum: "seqnum",
  MinusSeqnum: "-seqnum",
} as const;
export type FetchNodeLogsSortBy = ClosedEnum<typeof FetchNodeLogsSortBy>;

export type FetchNodeLogsRequest = {
  id: string;
  /**
   * Return logs with `seqnum` less than or equal to this value.
   */
  seqnumBefore?: number | undefined;
  /**
   * Return logs with `seqnum` greater than or equal to this value.
   */
  seqnumAfter?: number | undefined;
  /**
   * Due to clock synchronization, some earlier log messages may have a realtime timestamp after this value.
   */
  realtimeTimestampBefore?: number | undefined;
  /**
   * Due to clock synchronization, some later log messages may have a realtime timestamp before this value.
   */
  realtimeTimestampAfter?: number | undefined;
  sortBy?: FetchNodeLogsSortBy | undefined;
  limit?: number | undefined;
};

/** @internal */
export const FetchNodeLogsSortBy$outboundSchema: z.ZodMiniEnum<
  typeof FetchNodeLogsSortBy
> = z.enum(FetchNodeLogsSortBy);

/** @internal */
export type FetchNodeLogsRequest$Outbound = {
  id: string;
  seqnum_before?: number | undefined;
  seqnum_after?: number | undefined;
  realtime_timestamp_before?: number | undefined;
  realtime_timestamp_after?: number | undefined;
  sort_by?: string | undefined;
  limit: number;
};

/** @internal */
export const FetchNodeLogsRequest$outboundSchema: z.ZodMiniType<
  FetchNodeLogsRequest$Outbound,
  FetchNodeLogsRequest
> = z.pipe(
  z.object({
    id: z.string(),
    seqnumBefore: z.optional(z.int()),
    seqnumAfter: z.optional(z.int()),
    realtimeTimestampBefore: z.optional(z.int()),
    realtimeTimestampAfter: z.optional(z.int()),
    sortBy: z.optional(FetchNodeLogsSortBy$outboundSchema),
    limit: z._default(z.int(), 100),
  }),
  z.transform((v) => {
    return remap$(v, {
      seqnumBefore: "seqnum_before",
      seqnumAfter: "seqnum_after",
      realtimeTimestampBefore: "realtime_timestamp_before",
      realtimeTimestampAfter: "realtime_timestamp_after",
      sortBy: "sort_by",
    });
  }),
);

export function fetchNodeLogsRequestToJSON(
  fetchNodeLogsRequest: FetchNodeLogsRequest,
): string {
  return JSON.stringify(
    FetchNodeLogsRequest$outboundSchema.parse(fetchNodeLogsRequest),
  );
}
