/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";

export type FetchNodeRequest = {
  id: string;
};

/** @internal */
export type FetchNodeRequest$Outbound = {
  id: string;
};

/** @internal */
export const FetchNodeRequest$outboundSchema: z.ZodMiniType<
  FetchNodeRequest$Outbound,
  FetchNodeRequest
> = z.object({
  id: z.string(),
});

export function fetchNodeRequestToJSON(
  fetchNodeRequest: FetchNodeRequest,
): string {
  return JSON.stringify(
    FetchNodeRequest$outboundSchema.parse(fetchNodeRequest),
  );
}
