/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";

export type FetchCapacityRequest = {
  id: string;
};

/** @internal */
export type FetchCapacityRequest$Outbound = {
  id: string;
};

/** @internal */
export const FetchCapacityRequest$outboundSchema: z.ZodMiniType<
  FetchCapacityRequest$Outbound,
  FetchCapacityRequest
> = z.object({
  id: z.string(),
});

export function fetchCapacityRequestToJSON(
  fetchCapacityRequest: FetchCapacityRequest,
): string {
  return JSON.stringify(
    FetchCapacityRequest$outboundSchema.parse(fetchCapacityRequest),
  );
}
