/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";

export type FetchNodeTemplateRequest = {
  id: string;
};

/** @internal */
export type FetchNodeTemplateRequest$Outbound = {
  id: string;
};

/** @internal */
export const FetchNodeTemplateRequest$outboundSchema: z.ZodMiniType<
  FetchNodeTemplateRequest$Outbound,
  FetchNodeTemplateRequest
> = z.object({
  id: z.string(),
});

export function fetchNodeTemplateRequestToJSON(
  fetchNodeTemplateRequest: FetchNodeTemplateRequest,
): string {
  return JSON.stringify(
    FetchNodeTemplateRequest$outboundSchema.parse(fetchNodeTemplateRequest),
  );
}
