/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";

export type FetchOrderRequest = {
  /**
   * Order ID
   */
  id: string;
};

/** @internal */
export type FetchOrderRequest$Outbound = {
  id: string;
};

/** @internal */
export const FetchOrderRequest$outboundSchema: z.ZodMiniType<
  FetchOrderRequest$Outbound,
  FetchOrderRequest
> = z.object({
  id: z.string(),
});

export function fetchOrderRequestToJSON(
  fetchOrderRequest: FetchOrderRequest,
): string {
  return JSON.stringify(
    FetchOrderRequest$outboundSchema.parse(fetchOrderRequest),
  );
}
