/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";

export type GetImageSecurity = {
  vmorchBearerAuth: string;
};

export type GetImageRequest = {
  id: string;
};

/** @internal */
export type GetImageSecurity$Outbound = {
  vmorch_bearer_auth: string;
};

/** @internal */
export const GetImageSecurity$outboundSchema: z.ZodMiniType<
  GetImageSecurity$Outbound,
  GetImageSecurity
> = z.pipe(
  z.object({
    vmorchBearerAuth: z.string(),
  }),
  z.transform((v) => {
    return remap$(v, {
      vmorchBearerAuth: "vmorch_bearer_auth",
    });
  }),
);

export function getImageSecurityToJSON(
  getImageSecurity: GetImageSecurity,
): string {
  return JSON.stringify(
    GetImageSecurity$outboundSchema.parse(getImageSecurity),
  );
}

/** @internal */
export type GetImageRequest$Outbound = {
  id: string;
};

/** @internal */
export const GetImageRequest$outboundSchema: z.ZodMiniType<
  GetImageRequest$Outbound,
  GetImageRequest
> = z.object({
  id: z.string(),
});

export function getImageRequestToJSON(
  getImageRequest: GetImageRequest,
): string {
  return JSON.stringify(GetImageRequest$outboundSchema.parse(getImageRequest));
}
