/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";

export type GetCapacityHandlerRequest = {
  id: string;
};

/** @internal */
export type GetCapacityHandlerRequest$Outbound = {
  id: string;
};

/** @internal */
export const GetCapacityHandlerRequest$outboundSchema: z.ZodMiniType<
  GetCapacityHandlerRequest$Outbound,
  GetCapacityHandlerRequest
> = z.object({
  id: z.string(),
});

export function getCapacityHandlerRequestToJSON(
  getCapacityHandlerRequest: GetCapacityHandlerRequest,
): string {
  return JSON.stringify(
    GetCapacityHandlerRequest$outboundSchema.parse(getCapacityHandlerRequest),
  );
}
