/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";

export type GetNodeSecurity = {
  vmorchBearerAuth: string;
};

export type GetNodeRequest = {
  id: string;
};

/** @internal */
export type GetNodeSecurity$Outbound = {
  vmorch_bearer_auth: string;
};

/** @internal */
export const GetNodeSecurity$outboundSchema: z.ZodMiniType<
  GetNodeSecurity$Outbound,
  GetNodeSecurity
> = z.pipe(
  z.object({
    vmorchBearerAuth: z.string(),
  }),
  z.transform((v) => {
    return remap$(v, {
      vmorchBearerAuth: "vmorch_bearer_auth",
    });
  }),
);

export function getNodeSecurityToJSON(
  getNodeSecurity: GetNodeSecurity,
): string {
  return JSON.stringify(GetNodeSecurity$outboundSchema.parse(getNodeSecurity));
}

/** @internal */
export type GetNodeRequest$Outbound = {
  id: string;
};

/** @internal */
export const GetNodeRequest$outboundSchema: z.ZodMiniType<
  GetNodeRequest$Outbound,
  GetNodeRequest
> = z.object({
  id: z.string(),
});

export function getNodeRequestToJSON(getNodeRequest: GetNodeRequest): string {
  return JSON.stringify(GetNodeRequest$outboundSchema.parse(getNodeRequest));
}
