/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";

export type GetOrderRequest = {
  /**
   * Order ID
   */
  id: string;
};

/** @internal */
export type GetOrderRequest$Outbound = {
  id: string;
};

/** @internal */
export const GetOrderRequest$outboundSchema: z.ZodMiniType<
  GetOrderRequest$Outbound,
  GetOrderRequest
> = z.object({
  id: z.string(),
});

export function getOrderRequestToJSON(
  getOrderRequest: GetOrderRequest,
): string {
  return JSON.stringify(GetOrderRequest$outboundSchema.parse(getOrderRequest));
}
