/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";

export type GetNodeTemplateHandlerRequest = {
  id: string;
};

/** @internal */
export type GetNodeTemplateHandlerRequest$Outbound = {
  id: string;
};

/** @internal */
export const GetNodeTemplateHandlerRequest$outboundSchema: z.ZodMiniType<
  GetNodeTemplateHandlerRequest$Outbound,
  GetNodeTemplateHandlerRequest
> = z.object({
  id: z.string(),
});

export function getNodeTemplateHandlerRequestToJSON(
  getNodeTemplateHandlerRequest: GetNodeTemplateHandlerRequest,
): string {
  return JSON.stringify(
    GetNodeTemplateHandlerRequest$outboundSchema.parse(
      getNodeTemplateHandlerRequest,
    ),
  );
}
