/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";

export type GetNodeSshSecurity = {
  vmorchBearerAuth: string;
};

export type GetNodeSshRequest = {
  id: string;
};

/** @internal */
export type GetNodeSshSecurity$Outbound = {
  vmorch_bearer_auth: string;
};

/** @internal */
export const GetNodeSshSecurity$outboundSchema: z.ZodMiniType<
  GetNodeSshSecurity$Outbound,
  GetNodeSshSecurity
> = z.pipe(
  z.object({
    vmorchBearerAuth: z.string(),
  }),
  z.transform((v) => {
    return remap$(v, {
      vmorchBearerAuth: "vmorch_bearer_auth",
    });
  }),
);

export function getNodeSshSecurityToJSON(
  getNodeSshSecurity: GetNodeSshSecurity,
): string {
  return JSON.stringify(
    GetNodeSshSecurity$outboundSchema.parse(getNodeSshSecurity),
  );
}

/** @internal */
export type GetNodeSshRequest$Outbound = {
  id: string;
};

/** @internal */
export const GetNodeSshRequest$outboundSchema: z.ZodMiniType<
  GetNodeSshRequest$Outbound,
  GetNodeSshRequest
> = z.object({
  id: z.string(),
});

export function getNodeSshRequestToJSON(
  getNodeSshRequest: GetNodeSshRequest,
): string {
  return JSON.stringify(
    GetNodeSshRequest$outboundSchema.parse(getNodeSshRequest),
  );
}
