/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";

export type GetNodeSshRequest = {
  id: string;
};

/** @internal */
export type GetNodeSshRequest$Outbound = {
  id: string;
};

/** @internal */
export const GetNodeSshRequest$outboundSchema: z.ZodMiniType<
  GetNodeSshRequest$Outbound,
  GetNodeSshRequest
> = z.object({
  id: z.string(),
});

export function getNodeSshRequestToJSON(
  getNodeSshRequest: GetNodeSshRequest,
): string {
  return JSON.stringify(
    GetNodeSshRequest$outboundSchema.parse(getNodeSshRequest),
  );
}
