/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import { ClosedEnum } from "../../types/enums.js";

export type GetNodeLogsSecurity = {
  vmorchBearerAuth: string;
};

export const GetNodeLogsSortBy = {
  Seqnum: "seqnum",
  MinusSeqnum: "-seqnum",
} as const;
export type GetNodeLogsSortBy = ClosedEnum<typeof GetNodeLogsSortBy>;

export type GetNodeLogsRequest = {
  id: string;
  /**
   * Return logs with `seqnum` less than or equal to this value.
   */
  seqnumBefore?: number | undefined;
  /**
   * Return logs with `seqnum` greater than or equal to this value.
   */
  seqnumAfter?: number | undefined;
  /**
   * Due to clock synchronization, some earlier log messages may have a realtime timestamp after this value.
   */
  realtimeTimestampBefore?: number | undefined;
  /**
   * Due to clock synchronization, some later log messages may have a realtime timestamp before this value.
   */
  realtimeTimestampAfter?: number | undefined;
  sortBy?: GetNodeLogsSortBy | undefined;
  limit?: number | undefined;
};

/** @internal */
export type GetNodeLogsSecurity$Outbound = {
  vmorch_bearer_auth: string;
};

/** @internal */
export const GetNodeLogsSecurity$outboundSchema: z.ZodMiniType<
  GetNodeLogsSecurity$Outbound,
  GetNodeLogsSecurity
> = z.pipe(
  z.object({
    vmorchBearerAuth: z.string(),
  }),
  z.transform((v) => {
    return remap$(v, {
      vmorchBearerAuth: "vmorch_bearer_auth",
    });
  }),
);

export function getNodeLogsSecurityToJSON(
  getNodeLogsSecurity: GetNodeLogsSecurity,
): string {
  return JSON.stringify(
    GetNodeLogsSecurity$outboundSchema.parse(getNodeLogsSecurity),
  );
}

/** @internal */
export const GetNodeLogsSortBy$outboundSchema: z.ZodMiniEnum<
  typeof GetNodeLogsSortBy
> = z.enum(GetNodeLogsSortBy);

/** @internal */
export type GetNodeLogsRequest$Outbound = {
  id: string;
  seqnum_before?: number | undefined;
  seqnum_after?: number | undefined;
  realtime_timestamp_before?: number | undefined;
  realtime_timestamp_after?: number | undefined;
  sort_by?: string | undefined;
  limit: number;
};

/** @internal */
export const GetNodeLogsRequest$outboundSchema: z.ZodMiniType<
  GetNodeLogsRequest$Outbound,
  GetNodeLogsRequest
> = z.pipe(
  z.object({
    id: z.string(),
    seqnumBefore: z.optional(z.int()),
    seqnumAfter: z.optional(z.int()),
    realtimeTimestampBefore: z.optional(z.int()),
    realtimeTimestampAfter: z.optional(z.int()),
    sortBy: z.optional(GetNodeLogsSortBy$outboundSchema),
    limit: z._default(z.int(), 100),
  }),
  z.transform((v) => {
    return remap$(v, {
      seqnumBefore: "seqnum_before",
      seqnumAfter: "seqnum_after",
      realtimeTimestampBefore: "realtime_timestamp_before",
      realtimeTimestampAfter: "realtime_timestamp_after",
      sortBy: "sort_by",
    });
  }),
);

export function getNodeLogsRequestToJSON(
  getNodeLogsRequest: GetNodeLogsRequest,
): string {
  return JSON.stringify(
    GetNodeLogsRequest$outboundSchema.parse(getNodeLogsRequest),
  );
}
