/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import * as models from "../index.js";

export type ListNodesSecurity = {
  vmorchBearerAuth: string;
};

export type ListNodesRequest = {
  /**
   * Filter by node ID (repeatable).
   */
  id?: Array<string> | undefined;
  /**
   * Filter by capacity.
   */
  capacity?: string | undefined;
  /**
   * Filter by node status (repeatable).
   */
  status?: Array<models.VmorchNodeStatus> | undefined;
  /**
   * Include deleted nodes in the response. Currently terminated nodes are auto-deleted. Don't expect this behavior to be stable.
   */
  includeDeleted?: boolean | undefined;
  limit?: number | undefined;
  /**
   * Cursor for forward pagination (from a previous response's `cursor` field).
   */
  startingAfter?: string | undefined;
  /**
   * Cursor for backward pagination.
   */
  endingBefore?: string | undefined;
};

/** @internal */
export type ListNodesSecurity$Outbound = {
  vmorch_bearer_auth: string;
};

/** @internal */
export const ListNodesSecurity$outboundSchema: z.ZodMiniType<
  ListNodesSecurity$Outbound,
  ListNodesSecurity
> = z.pipe(
  z.object({
    vmorchBearerAuth: z.string(),
  }),
  z.transform((v) => {
    return remap$(v, {
      vmorchBearerAuth: "vmorch_bearer_auth",
    });
  }),
);

export function listNodesSecurityToJSON(
  listNodesSecurity: ListNodesSecurity,
): string {
  return JSON.stringify(
    ListNodesSecurity$outboundSchema.parse(listNodesSecurity),
  );
}

/** @internal */
export type ListNodesRequest$Outbound = {
  id?: Array<string> | undefined;
  capacity?: string | undefined;
  status?: Array<string> | undefined;
  include_deleted: boolean;
  limit: number;
  starting_after?: string | undefined;
  ending_before?: string | undefined;
};

/** @internal */
export const ListNodesRequest$outboundSchema: z.ZodMiniType<
  ListNodesRequest$Outbound,
  ListNodesRequest
> = z.pipe(
  z.object({
    id: z.optional(z.array(z.string())),
    capacity: z.optional(z.string()),
    status: z.optional(z.array(models.VmorchNodeStatus$outboundSchema)),
    includeDeleted: z._default(z.boolean(), false),
    limit: z._default(z.int(), 50),
    startingAfter: z.optional(z.string()),
    endingBefore: z.optional(z.string()),
  }),
  z.transform((v) => {
    return remap$(v, {
      includeDeleted: "include_deleted",
      startingAfter: "starting_after",
      endingBefore: "ending_before",
    });
  }),
);

export function listNodesRequestToJSON(
  listNodesRequest: ListNodesRequest,
): string {
  return JSON.stringify(
    ListNodesRequest$outboundSchema.parse(listNodesRequest),
  );
}
