/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";
import * as models from "../index.js";

export type ListNodeTemplatesRequest = {
  limit?: number | undefined;
  /**
   * Set to the response's `cursor` to fetch the next page.
   */
  startingAfter?: string | undefined;
  /**
   * Set to the response's `cursor` to fetch the previous page.
   */
  endingBefore?: string | undefined;
  includeDeleted?: boolean | undefined;
  /**
   * Additional fields to include in the response.
   */
  include?: Array<models.NodeTemplateInclude> | undefined;
};

export type ListNodeTemplatesResponse = {
  result: models.ListNodeTemplatesResponse;
};

/** @internal */
export type ListNodeTemplatesRequest$Outbound = {
  limit: number;
  starting_after?: string | undefined;
  ending_before?: string | undefined;
  include_deleted: boolean;
  include?: Array<string> | undefined;
};

/** @internal */
export const ListNodeTemplatesRequest$outboundSchema: z.ZodMiniType<
  ListNodeTemplatesRequest$Outbound,
  ListNodeTemplatesRequest
> = z.pipe(
  z.object({
    limit: z._default(z.int(), 50),
    startingAfter: z.optional(z.string()),
    endingBefore: z.optional(z.string()),
    includeDeleted: z._default(z.boolean(), false),
    include: z.optional(z.array(models.NodeTemplateInclude$outboundSchema)),
  }),
  z.transform((v) => {
    return remap$(v, {
      startingAfter: "starting_after",
      endingBefore: "ending_before",
      includeDeleted: "include_deleted",
    });
  }),
);

export function listNodeTemplatesRequestToJSON(
  listNodeTemplatesRequest: ListNodeTemplatesRequest,
): string {
  return JSON.stringify(
    ListNodeTemplatesRequest$outboundSchema.parse(listNodeTemplatesRequest),
  );
}

/** @internal */
export const ListNodeTemplatesResponse$inboundSchema: z.ZodMiniType<
  ListNodeTemplatesResponse,
  unknown
> = z.pipe(
  z.object({
    Result: models.ListNodeTemplatesResponse$inboundSchema,
  }),
  z.transform((v) => {
    return remap$(v, {
      "Result": "result",
    });
  }),
);

export function listNodeTemplatesResponseFromJSON(
  jsonString: string,
): SafeParseResult<ListNodeTemplatesResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ListNodeTemplatesResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ListNodeTemplatesResponse' from JSON`,
  );
}
