/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";
import * as models from "../index.js";

export type ListCapacitiesRequest = {
  limit?: number | undefined;
  /**
   * Set to the response's `cursor` to fetch the next page.
   */
  startingAfter?: string | undefined;
  /**
   * Set to the response's `cursor` to fetch the previous page.
   */
  endingBefore?: string | undefined;
  includeDeleted?: boolean | undefined;
};

export type ListCapacitiesResponse = {
  result: models.ListCapacitiesResponse;
};

/** @internal */
export type ListCapacitiesRequest$Outbound = {
  limit: number;
  starting_after?: string | undefined;
  ending_before?: string | undefined;
  include_deleted: boolean;
};

/** @internal */
export const ListCapacitiesRequest$outboundSchema: z.ZodMiniType<
  ListCapacitiesRequest$Outbound,
  ListCapacitiesRequest
> = z.pipe(
  z.object({
    limit: z._default(z.int(), 50),
    startingAfter: z.optional(z.string()),
    endingBefore: z.optional(z.string()),
    includeDeleted: z._default(z.boolean(), false),
  }),
  z.transform((v) => {
    return remap$(v, {
      startingAfter: "starting_after",
      endingBefore: "ending_before",
      includeDeleted: "include_deleted",
    });
  }),
);

export function listCapacitiesRequestToJSON(
  listCapacitiesRequest: ListCapacitiesRequest,
): string {
  return JSON.stringify(
    ListCapacitiesRequest$outboundSchema.parse(listCapacitiesRequest),
  );
}

/** @internal */
export const ListCapacitiesResponse$inboundSchema: z.ZodMiniType<
  ListCapacitiesResponse,
  unknown
> = z.pipe(
  z.object({
    Result: models.ListCapacitiesResponse$inboundSchema,
  }),
  z.transform((v) => {
    return remap$(v, {
      "Result": "result",
    });
  }),
);

export function listCapacitiesResponseFromJSON(
  jsonString: string,
): SafeParseResult<ListCapacitiesResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ListCapacitiesResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ListCapacitiesResponse' from JSON`,
  );
}
