/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import * as models from "../index.js";

/**
 * Prefix with `-` for descending.
 */
export type ListOrdersSortBy = models.MarketApiV2OrderSortBy;

export type ListOrdersRequest = {
  /**
   * Filter by capacity.
   */
  capacity?: string | undefined;
  side?: models.MarketApiSide | undefined;
  /**
   * Filter by status (repeatable).
   */
  status?: Array<models.MarketApiV2OrderStatus> | undefined;
  createdAfter?: number | undefined;
  createdBefore?: number | undefined;
  /**
   * Prefix with `-` for descending.
   */
  sortBy?: models.MarketApiV2OrderSortBy | undefined;
  limit?: number | undefined;
  /**
   * Set to the response's `cursor` to fetch the next page.
   */
  startingAfter?: string | undefined;
  /**
   * Set to the response's `cursor` to fetch the previous page.
   */
  endingBefore?: string | undefined;
};

/** @internal */
export type ListOrdersSortBy$Outbound = string;

/** @internal */
export const ListOrdersSortBy$outboundSchema: z.ZodMiniType<
  ListOrdersSortBy$Outbound,
  ListOrdersSortBy
> = models.MarketApiV2OrderSortBy$outboundSchema;

export function listOrdersSortByToJSON(
  listOrdersSortBy: ListOrdersSortBy,
): string {
  return JSON.stringify(
    ListOrdersSortBy$outboundSchema.parse(listOrdersSortBy),
  );
}

/** @internal */
export type ListOrdersRequest$Outbound = {
  capacity?: string | undefined;
  side?: string | undefined;
  status?: Array<string> | undefined;
  created_after?: number | undefined;
  created_before?: number | undefined;
  sort_by?: string | undefined;
  limit: number;
  starting_after?: string | undefined;
  ending_before?: string | undefined;
};

/** @internal */
export const ListOrdersRequest$outboundSchema: z.ZodMiniType<
  ListOrdersRequest$Outbound,
  ListOrdersRequest
> = z.pipe(
  z.object({
    capacity: z.optional(z.string()),
    side: z.optional(models.MarketApiSide$outboundSchema),
    status: z.optional(z.array(models.MarketApiV2OrderStatus$outboundSchema)),
    createdAfter: z.optional(z.int()),
    createdBefore: z.optional(z.int()),
    sortBy: z.optional(models.MarketApiV2OrderSortBy$outboundSchema),
    limit: z._default(z.int(), 50),
    startingAfter: z.optional(z.string()),
    endingBefore: z.optional(z.string()),
  }),
  z.transform((v) => {
    return remap$(v, {
      createdAfter: "created_after",
      createdBefore: "created_before",
      sortBy: "sort_by",
      startingAfter: "starting_after",
      endingBefore: "ending_before",
    });
  }),
);

export function listOrdersRequestToJSON(
  listOrdersRequest: ListOrdersRequest,
): string {
  return JSON.stringify(
    ListOrdersRequest$outboundSchema.parse(listOrdersRequest),
  );
}
