/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";
import * as models from "../index.js";

export type ListImagesRequest = {
  /**
   * Maximum number of results to return (1-200, default 50).
   */
  limit?: number | undefined;
  /**
   * Cursor for forward pagination (from a previous response's `cursor` field).
   */
  startingAfter?: string | undefined;
  /**
   * Cursor for backward pagination.
   */
  endingBefore?: string | undefined;
  /**
   * Include soft-deleted images in the results.
   */
  includeDeleted?: boolean | undefined;
};

export type ListImagesResponse = {
  result: models.ListImagesResponse;
};

/** @internal */
export type ListImagesRequest$Outbound = {
  limit: number;
  starting_after?: string | undefined;
  ending_before?: string | undefined;
  include_deleted: boolean;
};

/** @internal */
export const ListImagesRequest$outboundSchema: z.ZodMiniType<
  ListImagesRequest$Outbound,
  ListImagesRequest
> = z.pipe(
  z.object({
    limit: z._default(z.int(), 50),
    startingAfter: z.optional(z.string()),
    endingBefore: z.optional(z.string()),
    includeDeleted: z._default(z.boolean(), false),
  }),
  z.transform((v) => {
    return remap$(v, {
      startingAfter: "starting_after",
      endingBefore: "ending_before",
      includeDeleted: "include_deleted",
    });
  }),
);

export function listImagesRequestToJSON(
  listImagesRequest: ListImagesRequest,
): string {
  return JSON.stringify(
    ListImagesRequest$outboundSchema.parse(listImagesRequest),
  );
}

/** @internal */
export const ListImagesResponse$inboundSchema: z.ZodMiniType<
  ListImagesResponse,
  unknown
> = z.pipe(
  z.object({
    Result: models.ListImagesResponse$inboundSchema,
  }),
  z.transform((v) => {
    return remap$(v, {
      "Result": "result",
    });
  }),
);

export function listImagesResponseFromJSON(
  jsonString: string,
): SafeParseResult<ListImagesResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ListImagesResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ListImagesResponse' from JSON`,
  );
}
