/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";

export type ListNodeTemplatesHandlerRequest = {
  limit?: number | undefined;
  /**
   * Set to the response's `cursor` to fetch the next page.
   */
  startingAfter?: string | undefined;
  /**
   * Set to the response's `cursor` to fetch the previous page.
   */
  endingBefore?: string | undefined;
  includeDeleted?: boolean | undefined;
  /**
   * Additional fields to include in the response.
   */
  include?: Array<string> | undefined;
};

/** @internal */
export type ListNodeTemplatesHandlerRequest$Outbound = {
  limit: number;
  starting_after?: string | undefined;
  ending_before?: string | undefined;
  include_deleted: boolean;
  include?: Array<string> | undefined;
};

/** @internal */
export const ListNodeTemplatesHandlerRequest$outboundSchema: z.ZodMiniType<
  ListNodeTemplatesHandlerRequest$Outbound,
  ListNodeTemplatesHandlerRequest
> = z.pipe(
  z.object({
    limit: z._default(z.int(), 50),
    startingAfter: z.optional(z.string()),
    endingBefore: z.optional(z.string()),
    includeDeleted: z._default(z.boolean(), false),
    include: z.optional(z.array(z.string())),
  }),
  z.transform((v) => {
    return remap$(v, {
      startingAfter: "starting_after",
      endingBefore: "ending_before",
      includeDeleted: "include_deleted",
    });
  }),
);

export function listNodeTemplatesHandlerRequestToJSON(
  listNodeTemplatesHandlerRequest: ListNodeTemplatesHandlerRequest,
): string {
  return JSON.stringify(
    ListNodeTemplatesHandlerRequest$outboundSchema.parse(
      listNodeTemplatesHandlerRequest,
    ),
  );
}
