/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";

export type ListImagesV2Security = {
  vmorchBearerAuth: string;
};

export type ListImagesV2Request = {
  limit?: number | undefined;
  /**
   * Set to the response's `cursor` to fetch the next page.
   */
  startingAfter?: string | undefined;
  /**
   * Set to the response's `cursor` to fetch the previous page.
   */
  endingBefore?: string | undefined;
};

/** @internal */
export type ListImagesV2Security$Outbound = {
  vmorch_bearer_auth: string;
};

/** @internal */
export const ListImagesV2Security$outboundSchema: z.ZodMiniType<
  ListImagesV2Security$Outbound,
  ListImagesV2Security
> = z.pipe(
  z.object({
    vmorchBearerAuth: z.string(),
  }),
  z.transform((v) => {
    return remap$(v, {
      vmorchBearerAuth: "vmorch_bearer_auth",
    });
  }),
);

export function listImagesV2SecurityToJSON(
  listImagesV2Security: ListImagesV2Security,
): string {
  return JSON.stringify(
    ListImagesV2Security$outboundSchema.parse(listImagesV2Security),
  );
}

/** @internal */
export type ListImagesV2Request$Outbound = {
  limit: number;
  starting_after?: string | undefined;
  ending_before?: string | undefined;
};

/** @internal */
export const ListImagesV2Request$outboundSchema: z.ZodMiniType<
  ListImagesV2Request$Outbound,
  ListImagesV2Request
> = z.pipe(
  z.object({
    limit: z._default(z.int(), 50),
    startingAfter: z.optional(z.string()),
    endingBefore: z.optional(z.string()),
  }),
  z.transform((v) => {
    return remap$(v, {
      startingAfter: "starting_after",
      endingBefore: "ending_before",
    });
  }),
);

export function listImagesV2RequestToJSON(
  listImagesV2Request: ListImagesV2Request,
): string {
  return JSON.stringify(
    ListImagesV2Request$outboundSchema.parse(listImagesV2Request),
  );
}
