/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";

export type ListCapacitiesHandlerRequest = {
  limit?: number | undefined;
  /**
   * Set to the response's `cursor` to fetch the next page.
   */
  startingAfter?: string | undefined;
  /**
   * Set to the response's `cursor` to fetch the previous page.
   */
  endingBefore?: string | undefined;
  includeDeleted?: boolean | undefined;
};

/** @internal */
export type ListCapacitiesHandlerRequest$Outbound = {
  limit: number;
  starting_after?: string | undefined;
  ending_before?: string | undefined;
  include_deleted: boolean;
};

/** @internal */
export const ListCapacitiesHandlerRequest$outboundSchema: z.ZodMiniType<
  ListCapacitiesHandlerRequest$Outbound,
  ListCapacitiesHandlerRequest
> = z.pipe(
  z.object({
    limit: z._default(z.int(), 50),
    startingAfter: z.optional(z.string()),
    endingBefore: z.optional(z.string()),
    includeDeleted: z._default(z.boolean(), false),
  }),
  z.transform((v) => {
    return remap$(v, {
      startingAfter: "starting_after",
      endingBefore: "ending_before",
      includeDeleted: "include_deleted",
    });
  }),
);

export function listCapacitiesHandlerRequestToJSON(
  listCapacitiesHandlerRequest: ListCapacitiesHandlerRequest,
): string {
  return JSON.stringify(
    ListCapacitiesHandlerRequest$outboundSchema.parse(
      listCapacitiesHandlerRequest,
    ),
  );
}
