/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import * as models from "../index.js";

export type PatchCapacityHandlerRequest = {
  id: string;
  body: models.MarketApiPatchCapacityRequest;
};

/** @internal */
export type PatchCapacityHandlerRequest$Outbound = {
  id: string;
  body: models.MarketApiPatchCapacityRequest$Outbound;
};

/** @internal */
export const PatchCapacityHandlerRequest$outboundSchema: z.ZodMiniType<
  PatchCapacityHandlerRequest$Outbound,
  PatchCapacityHandlerRequest
> = z.object({
  id: z.string(),
  body: models.MarketApiPatchCapacityRequest$outboundSchema,
});

export function patchCapacityHandlerRequestToJSON(
  patchCapacityHandlerRequest: PatchCapacityHandlerRequest,
): string {
  return JSON.stringify(
    PatchCapacityHandlerRequest$outboundSchema.parse(
      patchCapacityHandlerRequest,
    ),
  );
}
