/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import * as models from "../index.js";

export type PostOrderRequest = {
  /**
   * Unique key to ensure idempotent order creation. If provided, duplicate requests with the same key will not place a new order and return the original order.
   */
  idempotencyKey?: string | null | undefined;
  body: models.MarketApiV2CreateOrderRequest;
};

/** @internal */
export type PostOrderRequest$Outbound = {
  "Idempotency-Key"?: string | null | undefined;
  body: models.MarketApiV2CreateOrderRequest$Outbound;
};

/** @internal */
export const PostOrderRequest$outboundSchema: z.ZodMiniType<
  PostOrderRequest$Outbound,
  PostOrderRequest
> = z.pipe(
  z.object({
    idempotencyKey: z.optional(z.nullable(z.string())),
    body: models.MarketApiV2CreateOrderRequest$outboundSchema,
  }),
  z.transform((v) => {
    return remap$(v, {
      idempotencyKey: "Idempotency-Key",
    });
  }),
);

export function postOrderRequestToJSON(
  postOrderRequest: PostOrderRequest,
): string {
  return JSON.stringify(
    PostOrderRequest$outboundSchema.parse(postOrderRequest),
  );
}
