/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import * as models from "../index.js";

export type ReplaceNodeRequest = {
  id: string;
  body: models.ReplaceNodeRequest;
};

/** @internal */
export type ReplaceNodeRequest$Outbound = {
  id: string;
  body: models.ReplaceNodeRequest$Outbound;
};

/** @internal */
export const ReplaceNodeRequest$outboundSchema: z.ZodMiniType<
  ReplaceNodeRequest$Outbound,
  ReplaceNodeRequest
> = z.object({
  id: z.string(),
  body: models.ReplaceNodeRequest$outboundSchema,
});

export function replaceNodeRequestToJSON(
  replaceNodeRequest: ReplaceNodeRequest,
): string {
  return JSON.stringify(
    ReplaceNodeRequest$outboundSchema.parse(replaceNodeRequest),
  );
}
