/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import * as models from "../index.js";

export type ReplaceNodeSecurity = {
  vmorchBearerAuth: string;
};

export type ReplaceNodeRequest = {
  id: string;
  body: models.VmorchReplaceNodeRequest;
};

/** @internal */
export type ReplaceNodeSecurity$Outbound = {
  vmorch_bearer_auth: string;
};

/** @internal */
export const ReplaceNodeSecurity$outboundSchema: z.ZodMiniType<
  ReplaceNodeSecurity$Outbound,
  ReplaceNodeSecurity
> = z.pipe(
  z.object({
    vmorchBearerAuth: z.string(),
  }),
  z.transform((v) => {
    return remap$(v, {
      vmorchBearerAuth: "vmorch_bearer_auth",
    });
  }),
);

export function replaceNodeSecurityToJSON(
  replaceNodeSecurity: ReplaceNodeSecurity,
): string {
  return JSON.stringify(
    ReplaceNodeSecurity$outboundSchema.parse(replaceNodeSecurity),
  );
}

/** @internal */
export type ReplaceNodeRequest$Outbound = {
  id: string;
  body: models.VmorchReplaceNodeRequest$Outbound;
};

/** @internal */
export const ReplaceNodeRequest$outboundSchema: z.ZodMiniType<
  ReplaceNodeRequest$Outbound,
  ReplaceNodeRequest
> = z.object({
  id: z.string(),
  body: models.VmorchReplaceNodeRequest$outboundSchema,
});

export function replaceNodeRequestToJSON(
  replaceNodeRequest: ReplaceNodeRequest,
): string {
  return JSON.stringify(
    ReplaceNodeRequest$outboundSchema.parse(replaceNodeRequest),
  );
}
