/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";

export type StartUploadSecurity = {
  vmorchBearerAuth: string;
};

/** @internal */
export type StartUploadSecurity$Outbound = {
  vmorch_bearer_auth: string;
};

/** @internal */
export const StartUploadSecurity$outboundSchema: z.ZodMiniType<
  StartUploadSecurity$Outbound,
  StartUploadSecurity
> = z.pipe(
  z.object({
    vmorchBearerAuth: z.string(),
  }),
  z.transform((v) => {
    return remap$(v, {
      vmorchBearerAuth: "vmorch_bearer_auth",
    });
  }),
);

export function startUploadSecurityToJSON(
  startUploadSecurity: StartUploadSecurity,
): string {
  return JSON.stringify(
    StartUploadSecurity$outboundSchema.parse(startUploadSecurity),
  );
}
