/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import * as models from "../index.js";

export type UpdateCapacityRequest = {
  id: string;
  body: models.PatchCapacityRequest;
};

/** @internal */
export type UpdateCapacityRequest$Outbound = {
  id: string;
  body: models.PatchCapacityRequest$Outbound;
};

/** @internal */
export const UpdateCapacityRequest$outboundSchema: z.ZodMiniType<
  UpdateCapacityRequest$Outbound,
  UpdateCapacityRequest
> = z.object({
  id: z.string(),
  body: models.PatchCapacityRequest$outboundSchema,
});

export function updateCapacityRequestToJSON(
  updateCapacityRequest: UpdateCapacityRequest,
): string {
  return JSON.stringify(
    UpdateCapacityRequest$outboundSchema.parse(updateCapacityRequest),
  );
}
