/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import * as models from "../index.js";

export type UploadPartSecurity = {
  vmorchBearerAuth: string;
};

export type UploadPartRequest = {
  id: string;
  body: models.VmorchUploadPartRequest;
};

/** @internal */
export type UploadPartSecurity$Outbound = {
  vmorch_bearer_auth: string;
};

/** @internal */
export const UploadPartSecurity$outboundSchema: z.ZodMiniType<
  UploadPartSecurity$Outbound,
  UploadPartSecurity
> = z.pipe(
  z.object({
    vmorchBearerAuth: z.string(),
  }),
  z.transform((v) => {
    return remap$(v, {
      vmorchBearerAuth: "vmorch_bearer_auth",
    });
  }),
);

export function uploadPartSecurityToJSON(
  uploadPartSecurity: UploadPartSecurity,
): string {
  return JSON.stringify(
    UploadPartSecurity$outboundSchema.parse(uploadPartSecurity),
  );
}

/** @internal */
export type UploadPartRequest$Outbound = {
  id: string;
  body: models.VmorchUploadPartRequest$Outbound;
};

/** @internal */
export const UploadPartRequest$outboundSchema: z.ZodMiniType<
  UploadPartRequest$Outbound,
  UploadPartRequest
> = z.object({
  id: z.string(),
  body: models.VmorchUploadPartRequest$outboundSchema,
});

export function uploadPartRequestToJSON(
  uploadPartRequest: UploadPartRequest,
): string {
  return JSON.stringify(
    UploadPartRequest$outboundSchema.parse(uploadPartRequest),
  );
}
