/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";
import {
  ScheduleEntry,
  ScheduleEntry$inboundSchema,
} from "./schedule-entry.js";

export type AllocationSchedule = {
  /**
   * Capacity availability over time.
   */
  total: Array<ScheduleEntry>;
  /**
   * Allocation schedule on a zone-by-zone basis. Only includes current and future schedule.
   */
  byZone: { [k: string]: Array<ScheduleEntry> };
};

/** @internal */
export const AllocationSchedule$inboundSchema: z.ZodMiniType<
  AllocationSchedule,
  unknown
> = z.pipe(
  z.object({
    total: z.array(ScheduleEntry$inboundSchema),
    by_zone: z.record(z.string(), z.array(ScheduleEntry$inboundSchema)),
  }),
  z.transform((v) => {
    return remap$(v, {
      "by_zone": "byZone",
    });
  }),
);

export function allocationScheduleFromJSON(
  jsonString: string,
): SafeParseResult<AllocationSchedule, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => AllocationSchedule$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'AllocationSchedule' from JSON`,
  );
}
