/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { ErrorDetail, ErrorDetail$inboundSchema } from "./error-detail.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";

export type BadRequestErrorError = {
  type: "invalid_request_error";
  message: string;
  details?: Array<ErrorDetail> | undefined;
};

/** @internal */
export const BadRequestErrorError$inboundSchema: z.ZodMiniType<
  BadRequestErrorError,
  unknown
> = z.object({
  type: z._default(
    types.literal("invalid_request_error"),
    "invalid_request_error",
  ),
  message: types.string(),
  details: types.optional(z.array(ErrorDetail$inboundSchema)),
});

export function badRequestErrorErrorFromJSON(
  jsonString: string,
): SafeParseResult<BadRequestErrorError, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => BadRequestErrorError$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'BadRequestErrorError' from JSON`,
  );
}
