/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import { ClosedEnum } from "../types/enums.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import {
  AllocationSchedule,
  AllocationSchedule$inboundSchema,
} from "./allocation-schedule.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";
import {
  SchedulerDetails,
  SchedulerDetails$inboundSchema,
} from "./scheduler-details.js";

export const CapacityResponseObject = {
  Capacity: "capacity",
} as const;
export type CapacityResponseObject = ClosedEnum<typeof CapacityResponseObject>;

export type CapacityResponse = {
  object: CapacityResponseObject;
  id: string;
  name?: string | null | undefined;
  /**
   * Datacenter locations orders into this capacity can acquire compute from.
   */
  zones: Array<string>;
  nodeTemplate?: string | null | undefined;
  /**
   * If enabled, nodes will be provisioned and terminated + deleted
   *
   * @remarks
   * automatically based on currently available allocation in this capacity.
   * Requires `node_template` to be set.
   */
  startNodesAutomatically: boolean;
  allocationSchedule: AllocationSchedule;
  /**
   * Unix timestamp.
   */
  createdAt: number;
  /**
   * Schedulers automatically place buy and sell orders to
   *
   * @remarks
   * attempt to achieve desired compute availability.
   */
  scheduler?: SchedulerDetails | undefined;
};

/** @internal */
export const CapacityResponseObject$inboundSchema: z.ZodMiniEnum<
  typeof CapacityResponseObject
> = z.enum(CapacityResponseObject);

/** @internal */
export const CapacityResponse$inboundSchema: z.ZodMiniType<
  CapacityResponse,
  unknown
> = z.pipe(
  z.object({
    object: CapacityResponseObject$inboundSchema,
    id: types.string(),
    name: z.optional(z.nullable(types.string())),
    zones: z.array(types.string()),
    node_template: z.optional(z.nullable(types.string())),
    start_nodes_automatically: types.boolean(),
    allocation_schedule: AllocationSchedule$inboundSchema,
    created_at: types.number(),
    scheduler: types.optional(SchedulerDetails$inboundSchema),
  }),
  z.transform((v) => {
    return remap$(v, {
      "node_template": "nodeTemplate",
      "start_nodes_automatically": "startNodesAutomatically",
      "allocation_schedule": "allocationSchedule",
      "created_at": "createdAt",
    });
  }),
);

export function capacityResponseFromJSON(
  jsonString: string,
): SafeParseResult<CapacityResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => CapacityResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'CapacityResponse' from JSON`,
  );
}
