/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";

/**
 * Complete a multipart image upload.
 */
export type CompleteUploadRequest = {
  /**
   * Not verified on upload; used during node boot to verify integrity.
   */
  sha256: string;
};

/** @internal */
export type CompleteUploadRequest$Outbound = {
  sha256: string;
};

/** @internal */
export const CompleteUploadRequest$outboundSchema: z.ZodMiniType<
  CompleteUploadRequest$Outbound,
  CompleteUploadRequest
> = z.object({
  sha256: z.string(),
});

export function completeUploadRequestToJSON(
  completeUploadRequest: CompleteUploadRequest,
): string {
  return JSON.stringify(
    CompleteUploadRequest$outboundSchema.parse(completeUploadRequest),
  );
}
