/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { ErrorDetail, ErrorDetail$inboundSchema } from "./error-detail.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";

export type ConflictErrorError = {
  type: "conflict";
  message: string;
  details?: Array<ErrorDetail> | undefined;
};

/** @internal */
export const ConflictErrorError$inboundSchema: z.ZodMiniType<
  ConflictErrorError,
  unknown
> = z.object({
  type: z._default(types.literal("conflict"), "conflict"),
  message: types.string(),
  details: types.optional(z.array(ErrorDetail$inboundSchema)),
});

export function conflictErrorErrorFromJSON(
  jsonString: string,
): SafeParseResult<ConflictErrorError, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ConflictErrorError$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ConflictErrorError' from JSON`,
  );
}
