/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../lib/schemas.js";
import { ClosedEnum } from "../types/enums.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { ErrorDetail, ErrorDetail$inboundSchema } from "./error-detail.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";

export const ConflictErrorType = {
  Conflict: "conflict",
} as const;
export type ConflictErrorType = ClosedEnum<typeof ConflictErrorType>;

export type ConflictErrorError = {
  type: ConflictErrorType;
  message: string;
  details?: Array<ErrorDetail> | undefined;
};

/** @internal */
export const ConflictErrorType$inboundSchema: z.ZodMiniEnum<
  typeof ConflictErrorType
> = z.enum(ConflictErrorType);

/** @internal */
export const ConflictErrorError$inboundSchema: z.ZodMiniType<
  ConflictErrorError,
  unknown
> = z.object({
  type: ConflictErrorType$inboundSchema,
  message: types.string(),
  details: types.optional(z.array(ErrorDetail$inboundSchema)),
});

export function conflictErrorErrorFromJSON(
  jsonString: string,
): SafeParseResult<ConflictErrorError, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ConflictErrorError$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ConflictErrorError' from JSON`,
  );
}
