/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";

export type DeleteImageResponse = {
  object: "image";
  deleted: boolean;
  name: string;
};

/** @internal */
export const DeleteImageResponse$inboundSchema: z.ZodMiniType<
  DeleteImageResponse,
  unknown
> = z.object({
  object: z._default(types.literal("image"), "image"),
  deleted: types.boolean(),
  name: types.string(),
});

export function deleteImageResponseFromJSON(
  jsonString: string,
): SafeParseResult<DeleteImageResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => DeleteImageResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'DeleteImageResponse' from JSON`,
  );
}
