/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";

export type ForbiddenErrorError = {
  type: "forbidden";
  message: string;
};

/** @internal */
export const ForbiddenErrorError$inboundSchema: z.ZodMiniType<
  ForbiddenErrorError,
  unknown
> = z.object({
  type: z._default(types.literal("forbidden"), "forbidden"),
  message: types.string(),
});

export function forbiddenErrorErrorFromJSON(
  jsonString: string,
): SafeParseResult<ForbiddenErrorError, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ForbiddenErrorError$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ForbiddenErrorError' from JSON`,
  );
}
