/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../lib/schemas.js";
import { ClosedEnum } from "../types/enums.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { ErrorDetail, ErrorDetail$inboundSchema } from "./error-detail.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";

export const ForbiddenErrorType = {
  Forbidden: "forbidden",
} as const;
export type ForbiddenErrorType = ClosedEnum<typeof ForbiddenErrorType>;

export type ForbiddenErrorError = {
  type: ForbiddenErrorType;
  message: string;
  details?: Array<ErrorDetail> | undefined;
};

/** @internal */
export const ForbiddenErrorType$inboundSchema: z.ZodMiniEnum<
  typeof ForbiddenErrorType
> = z.enum(ForbiddenErrorType);

/** @internal */
export const ForbiddenErrorError$inboundSchema: z.ZodMiniType<
  ForbiddenErrorError,
  unknown
> = z.object({
  type: ForbiddenErrorType$inboundSchema,
  message: types.string(),
  details: types.optional(z.array(ErrorDetail$inboundSchema)),
});

export function forbiddenErrorErrorFromJSON(
  jsonString: string,
): SafeParseResult<ForbiddenErrorError, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ForbiddenErrorError$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ForbiddenErrorError' from JSON`,
  );
}
