/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";
import {
  ImageUploadStatus,
  ImageUploadStatus$inboundSchema,
} from "./image-upload-status.js";

export type ImageListEntry = {
  object: "image";
  id: string;
  name: string;
  uploadStatus: ImageUploadStatus;
  /**
   * Unix timestamp.
   */
  createdAt: number;
  provider?: string | null | undefined;
  sha256?: string | null | undefined;
};

/** @internal */
export const ImageListEntry$inboundSchema: z.ZodMiniType<
  ImageListEntry,
  unknown
> = z.pipe(
  z.object({
    object: z._default(types.literal("image"), "image"),
    id: types.string(),
    name: types.string(),
    upload_status: ImageUploadStatus$inboundSchema,
    created_at: types.number(),
    provider: z.optional(z.nullable(types.string())),
    sha256: z.optional(z.nullable(types.string())),
  }),
  z.transform((v) => {
    return remap$(v, {
      "upload_status": "uploadStatus",
      "created_at": "createdAt",
    });
  }),
);

export function imageListEntryFromJSON(
  jsonString: string,
): SafeParseResult<ImageListEntry, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ImageListEntry$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ImageListEntry' from JSON`,
  );
}
