/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";
import {
  ImageUploadStatus,
  ImageUploadStatus$inboundSchema,
} from "./image-upload-status.js";

export type ImageUploadResponse = {
  object: "image";
  id: string;
  name: string;
  uploadStatus: ImageUploadStatus;
  sha256?: string | null | undefined;
  /**
   * Unix timestamp.
   */
  createdAt: number;
};

/** @internal */
export const ImageUploadResponse$inboundSchema: z.ZodMiniType<
  ImageUploadResponse,
  unknown
> = z.pipe(
  z.object({
    object: z._default(types.literal("image"), "image"),
    id: types.string(),
    name: types.string(),
    upload_status: ImageUploadStatus$inboundSchema,
    sha256: z.optional(z.nullable(types.string())),
    created_at: types.number(),
  }),
  z.transform((v) => {
    return remap$(v, {
      "upload_status": "uploadStatus",
      "created_at": "createdAt",
    });
  }),
);

export function imageUploadResponseFromJSON(
  jsonString: string,
): SafeParseResult<ImageUploadResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ImageUploadResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ImageUploadResponse' from JSON`,
  );
}
