/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import * as openEnums from "../types/enums.js";
import { OpenEnum } from "../types/enums.js";

export const ImageUploadStatus = {
  Started: "started",
  Uploading: "uploading",
  Completed: "completed",
  Failed: "failed",
} as const;
export type ImageUploadStatus = OpenEnum<typeof ImageUploadStatus>;

/** @internal */
export const ImageUploadStatus$inboundSchema: z.ZodMiniType<
  ImageUploadStatus,
  unknown
> = openEnums.inboundSchema(ImageUploadStatus);
