/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { ErrorDetail, ErrorDetail$inboundSchema } from "./error-detail.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";

export type InternalServerErrorError = {
  type: "api_error";
  message: string;
  details?: Array<ErrorDetail> | undefined;
};

/** @internal */
export const InternalServerErrorError$inboundSchema: z.ZodMiniType<
  InternalServerErrorError,
  unknown
> = z.object({
  type: z._default(types.literal("api_error"), "api_error"),
  message: types.string(),
  details: types.optional(z.array(ErrorDetail$inboundSchema)),
});

export function internalServerErrorErrorFromJSON(
  jsonString: string,
): SafeParseResult<InternalServerErrorError, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => InternalServerErrorError$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'InternalServerErrorError' from JSON`,
  );
}
