/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../lib/schemas.js";
import { ClosedEnum } from "../types/enums.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { ErrorDetail, ErrorDetail$inboundSchema } from "./error-detail.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";

export const InternalServerErrorType = {
  ApiError: "api_error",
} as const;
export type InternalServerErrorType = ClosedEnum<
  typeof InternalServerErrorType
>;

export type InternalServerErrorError = {
  type: InternalServerErrorType;
  message: string;
  details?: Array<ErrorDetail> | undefined;
};

/** @internal */
export const InternalServerErrorType$inboundSchema: z.ZodMiniEnum<
  typeof InternalServerErrorType
> = z.enum(InternalServerErrorType);

/** @internal */
export const InternalServerErrorError$inboundSchema: z.ZodMiniType<
  InternalServerErrorError,
  unknown
> = z.object({
  type: InternalServerErrorType$inboundSchema,
  message: types.string(),
  details: types.optional(z.array(ErrorDetail$inboundSchema)),
});

export function internalServerErrorErrorFromJSON(
  jsonString: string,
): SafeParseResult<InternalServerErrorError, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => InternalServerErrorError$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'InternalServerErrorError' from JSON`,
  );
}
