/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";
import {
  ImageListEntry,
  ImageListEntry$inboundSchema,
} from "./image-list-entry.js";

export type ListImagesResponse = {
  object: "list";
  cursor?: string | null | undefined;
  hasMore: boolean;
  data: Array<ImageListEntry>;
};

/** @internal */
export const ListImagesResponse$inboundSchema: z.ZodMiniType<
  ListImagesResponse,
  unknown
> = z.pipe(
  z.object({
    object: z._default(types.literal("list"), "list"),
    cursor: z.optional(z.nullable(types.string())),
    has_more: types.boolean(),
    data: z.array(ImageListEntry$inboundSchema),
  }),
  z.transform((v) => {
    return remap$(v, {
      "has_more": "hasMore",
    });
  }),
);

export function listImagesResponseFromJSON(
  jsonString: string,
): SafeParseResult<ListImagesResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ListImagesResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ListImagesResponse' from JSON`,
  );
}
