/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import {
  CapacityResponse,
  CapacityResponse$inboundSchema,
} from "./capacity-response.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";

export type ListCapacitiesResponse = {
  object: "list";
  cursor?: string | undefined;
  hasMore: boolean;
  data: Array<CapacityResponse>;
};

/** @internal */
export const ListCapacitiesResponse$inboundSchema: z.ZodMiniType<
  ListCapacitiesResponse,
  unknown
> = z.pipe(
  z.object({
    object: z._default(types.literal("list"), "list"),
    cursor: types.optional(types.string()),
    has_more: types.boolean(),
    data: z.array(CapacityResponse$inboundSchema),
  }),
  z.transform((v) => {
    return remap$(v, {
      "has_more": "hasMore",
    });
  }),
);

export function listCapacitiesResponseFromJSON(
  jsonString: string,
): SafeParseResult<ListCapacitiesResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ListCapacitiesResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ListCapacitiesResponse' from JSON`,
  );
}
