/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import { ClosedEnum } from "../types/enums.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";
import {
  NodeTemplateResponse,
  NodeTemplateResponse$inboundSchema,
} from "./node-template-response.js";

export const ListNodeTemplatesResponseObject = {
  List: "list",
} as const;
export type ListNodeTemplatesResponseObject = ClosedEnum<
  typeof ListNodeTemplatesResponseObject
>;

export type ListNodeTemplatesResponse = {
  object: ListNodeTemplatesResponseObject;
  cursor?: string | null | undefined;
  hasMore: boolean;
  data: Array<NodeTemplateResponse>;
};

/** @internal */
export const ListNodeTemplatesResponseObject$inboundSchema: z.ZodMiniEnum<
  typeof ListNodeTemplatesResponseObject
> = z.enum(ListNodeTemplatesResponseObject);

/** @internal */
export const ListNodeTemplatesResponse$inboundSchema: z.ZodMiniType<
  ListNodeTemplatesResponse,
  unknown
> = z.pipe(
  z.object({
    object: ListNodeTemplatesResponseObject$inboundSchema,
    cursor: z.optional(z.nullable(types.string())),
    has_more: types.boolean(),
    data: z.array(NodeTemplateResponse$inboundSchema),
  }),
  z.transform((v) => {
    return remap$(v, {
      "has_more": "hasMore",
    });
  }),
);

export function listNodeTemplatesResponseFromJSON(
  jsonString: string,
): SafeParseResult<ListNodeTemplatesResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ListNodeTemplatesResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ListNodeTemplatesResponse' from JSON`,
  );
}
