/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";
import { NodeResponse, NodeResponse$inboundSchema } from "./node-response.js";

export type ListNodesResponse = {
  object: "list";
  cursor?: string | null | undefined;
  hasMore: boolean;
  data: Array<NodeResponse>;
};

/** @internal */
export const ListNodesResponse$inboundSchema: z.ZodMiniType<
  ListNodesResponse,
  unknown
> = z.pipe(
  z.object({
    object: z._default(types.literal("list"), "list"),
    cursor: z.optional(z.nullable(types.string())),
    has_more: types.boolean(),
    data: z.array(NodeResponse$inboundSchema),
  }),
  z.transform((v) => {
    return remap$(v, {
      "has_more": "hasMore",
    });
  }),
);

export function listNodesResponseFromJSON(
  jsonString: string,
): SafeParseResult<ListNodesResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ListNodesResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ListNodesResponse' from JSON`,
  );
}
