/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import { ClosedEnum } from "../types/enums.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import {
  CapacityResponse,
  CapacityResponse$inboundSchema,
} from "./capacity-response.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";

export const ListCapacitiesResponseObject = {
  List: "list",
} as const;
export type ListCapacitiesResponseObject = ClosedEnum<
  typeof ListCapacitiesResponseObject
>;

export type ListCapacitiesResponse = {
  object: ListCapacitiesResponseObject;
  cursor?: string | null | undefined;
  hasMore: boolean;
  data: Array<CapacityResponse>;
};

/** @internal */
export const ListCapacitiesResponseObject$inboundSchema: z.ZodMiniEnum<
  typeof ListCapacitiesResponseObject
> = z.enum(ListCapacitiesResponseObject);

/** @internal */
export const ListCapacitiesResponse$inboundSchema: z.ZodMiniType<
  ListCapacitiesResponse,
  unknown
> = z.pipe(
  z.object({
    object: ListCapacitiesResponseObject$inboundSchema,
    cursor: z.optional(z.nullable(types.string())),
    has_more: types.boolean(),
    data: z.array(CapacityResponse$inboundSchema),
  }),
  z.transform((v) => {
    return remap$(v, {
      "has_more": "hasMore",
    });
  }),
);

export function listCapacitiesResponseFromJSON(
  jsonString: string,
): SafeParseResult<ListCapacitiesResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ListCapacitiesResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ListCapacitiesResponse' from JSON`,
  );
}
