/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";
import {
  MarketApiScheduleEntry,
  MarketApiScheduleEntry$inboundSchema,
} from "./market-api-schedule-entry.js";

export type MarketApiAllocationSchedule = {
  /**
   * Capacity availability over time.
   */
  total: Array<MarketApiScheduleEntry>;
  /**
   * Allocation schedule on a zone-by-zone basis. Only includes current and future schedule.
   */
  byZone: { [k: string]: Array<MarketApiScheduleEntry> };
};

/** @internal */
export const MarketApiAllocationSchedule$inboundSchema: z.ZodMiniType<
  MarketApiAllocationSchedule,
  unknown
> = z.pipe(
  z.object({
    total: z.array(MarketApiScheduleEntry$inboundSchema),
    by_zone: z.record(
      z.string(),
      z.array(MarketApiScheduleEntry$inboundSchema),
    ),
  }),
  z.transform((v) => {
    return remap$(v, {
      "by_zone": "byZone",
    });
  }),
);

export function marketApiAllocationScheduleFromJSON(
  jsonString: string,
): SafeParseResult<MarketApiAllocationSchedule, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => MarketApiAllocationSchedule$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'MarketApiAllocationSchedule' from JSON`,
  );
}
