/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";
import {
  MarketApiErrorDetail,
  MarketApiErrorDetail$inboundSchema,
} from "./market-api-error-detail.js";

export type MarketApiPaymentRequiredErrorError = {
  type: "payment_required";
  message: string;
  details?: Array<MarketApiErrorDetail> | undefined;
};

/** @internal */
export const MarketApiPaymentRequiredErrorError$inboundSchema: z.ZodMiniType<
  MarketApiPaymentRequiredErrorError,
  unknown
> = z.object({
  type: z._default(types.literal("payment_required"), "payment_required"),
  message: types.string(),
  details: types.optional(z.array(MarketApiErrorDetail$inboundSchema)),
});

export function marketApiPaymentRequiredErrorErrorFromJSON(
  jsonString: string,
): SafeParseResult<MarketApiPaymentRequiredErrorError, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      MarketApiPaymentRequiredErrorError$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'MarketApiPaymentRequiredErrorError' from JSON`,
  );
}
