/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { ClosedEnum } from "../types/enums.js";

export const MarketApiV2OrderSortBy = {
  CreatedAt: "created_at",
  MinusCreatedAt: "-created_at",
  StartAt: "start_at",
  MinusStartAt: "-start_at",
} as const;
export type MarketApiV2OrderSortBy = ClosedEnum<typeof MarketApiV2OrderSortBy>;

/** @internal */
export const MarketApiV2OrderSortBy$outboundSchema: z.ZodMiniEnum<
  typeof MarketApiV2OrderSortBy
> = z.enum(MarketApiV2OrderSortBy);
