/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import * as openEnums from "../types/enums.js";
import { OpenEnum } from "../types/enums.js";

export const MarketApiSide = {
  Sell: "sell",
  Buy: "buy",
} as const;
export type MarketApiSide = OpenEnum<typeof MarketApiSide>;

/** @internal */
export const MarketApiSide$inboundSchema: z.ZodMiniType<
  MarketApiSide,
  unknown
> = openEnums.inboundSchema(MarketApiSide);
/** @internal */
export const MarketApiSide$outboundSchema: z.ZodMiniType<
  string,
  MarketApiSide
> = openEnums.outboundSchema(MarketApiSide);
