/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../lib/primitives.js";
import {
  MarketApiSchedulerDetailsInputUnion,
  MarketApiSchedulerDetailsInputUnion$Outbound,
  MarketApiSchedulerDetailsInputUnion$outboundSchema,
} from "./market-api-scheduler-details-input-union.js";

export type MarketApiPatchCapacityRequest = {
  /**
   * Unique name for this capacity. Set to null to clear.
   */
  name?: string | null | undefined;
  /**
   * Datacenter locations orders into this capacity can acquire compute from. Replaces existing zones. Does not affect already scheduled compute.
   */
  zones?: Array<string> | null | undefined;
  /**
   * Template applied when nodes are automatically provisioned within the capacity. The template is not applied to pre-existing nodes.
   */
  nodeTemplate?: string | null | undefined;
  /**
   * Automatically provision and terminate nodes based on currently available allocation. Requires `node_template` to be set.
   */
  startNodesAutomatically?: boolean | null | undefined;
  /**
   * Schedulers automatically place buy and sell orders to attempt to achieve desired compute availability.
   */
  scheduler?: MarketApiSchedulerDetailsInputUnion | undefined;
};

/** @internal */
export type MarketApiPatchCapacityRequest$Outbound = {
  name?: string | null | undefined;
  zones?: Array<string> | null | undefined;
  node_template?: string | null | undefined;
  start_nodes_automatically?: boolean | null | undefined;
  scheduler?: MarketApiSchedulerDetailsInputUnion$Outbound | undefined;
};

/** @internal */
export const MarketApiPatchCapacityRequest$outboundSchema: z.ZodMiniType<
  MarketApiPatchCapacityRequest$Outbound,
  MarketApiPatchCapacityRequest
> = z.pipe(
  z.object({
    name: z.optional(z.nullable(z.string())),
    zones: z.optional(z.nullable(z.array(z.string()))),
    nodeTemplate: z.optional(z.nullable(z.string())),
    startNodesAutomatically: z.optional(z.nullable(z.boolean())),
    scheduler: z.optional(MarketApiSchedulerDetailsInputUnion$outboundSchema),
  }),
  z.transform((v) => {
    return remap$(v, {
      nodeTemplate: "node_template",
      startNodesAutomatically: "start_nodes_automatically",
    });
  }),
);

export function marketApiPatchCapacityRequestToJSON(
  marketApiPatchCapacityRequest: MarketApiPatchCapacityRequest,
): string {
  return JSON.stringify(
    MarketApiPatchCapacityRequest$outboundSchema.parse(
      marketApiPatchCapacityRequest,
    ),
  );
}
