/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";
import {
  MarketApiErrorDetail,
  MarketApiErrorDetail$inboundSchema,
} from "./market-api-error-detail.js";

export type MarketApiNotFoundErrorError = {
  type: "not_found";
  message: string;
  details?: Array<MarketApiErrorDetail> | undefined;
};

/** @internal */
export const MarketApiNotFoundErrorError$inboundSchema: z.ZodMiniType<
  MarketApiNotFoundErrorError,
  unknown
> = z.object({
  type: z._default(types.literal("not_found"), "not_found"),
  message: types.string(),
  details: types.optional(z.array(MarketApiErrorDetail$inboundSchema)),
});

export function marketApiNotFoundErrorErrorFromJSON(
  jsonString: string,
): SafeParseResult<MarketApiNotFoundErrorError, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => MarketApiNotFoundErrorError$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'MarketApiNotFoundErrorError' from JSON`,
  );
}
