/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";
import {
  MarketApiErrorDetail,
  MarketApiErrorDetail$inboundSchema,
} from "./market-api-error-detail.js";

export type MarketApiForbiddenErrorError = {
  type: "forbidden";
  message: string;
  details?: Array<MarketApiErrorDetail> | undefined;
};

/** @internal */
export const MarketApiForbiddenErrorError$inboundSchema: z.ZodMiniType<
  MarketApiForbiddenErrorError,
  unknown
> = z.object({
  type: z._default(types.literal("forbidden"), "forbidden"),
  message: types.string(),
  details: types.optional(z.array(MarketApiErrorDetail$inboundSchema)),
});

export function marketApiForbiddenErrorErrorFromJSON(
  jsonString: string,
): SafeParseResult<MarketApiForbiddenErrorError, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => MarketApiForbiddenErrorError$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'MarketApiForbiddenErrorError' from JSON`,
  );
}
