/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";
import {
  MarketApiErrorDetail,
  MarketApiErrorDetail$inboundSchema,
} from "./market-api-error-detail.js";

export type MarketApiUnauthorizedErrorError = {
  type: "authentication_error";
  message: string;
  details?: Array<MarketApiErrorDetail> | undefined;
};

/** @internal */
export const MarketApiUnauthorizedErrorError$inboundSchema: z.ZodMiniType<
  MarketApiUnauthorizedErrorError,
  unknown
> = z.object({
  type: z._default(
    types.literal("authentication_error"),
    "authentication_error",
  ),
  message: types.string(),
  details: types.optional(z.array(MarketApiErrorDetail$inboundSchema)),
});

export function marketApiUnauthorizedErrorErrorFromJSON(
  jsonString: string,
): SafeParseResult<MarketApiUnauthorizedErrorError, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => MarketApiUnauthorizedErrorError$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'MarketApiUnauthorizedErrorError' from JSON`,
  );
}
