/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";
import {
  MarketApiErrorDetail,
  MarketApiErrorDetail$inboundSchema,
} from "./market-api-error-detail.js";

export type MarketApiUnprocessableEntityErrorError = {
  type: "unprocessable_entity";
  message: string;
  details?: Array<MarketApiErrorDetail> | undefined;
};

/** @internal */
export const MarketApiUnprocessableEntityErrorError$inboundSchema:
  z.ZodMiniType<MarketApiUnprocessableEntityErrorError, unknown> = z.object({
    type: z._default(
      types.literal("unprocessable_entity"),
      "unprocessable_entity",
    ),
    message: types.string(),
    details: types.optional(z.array(MarketApiErrorDetail$inboundSchema)),
  });

export function marketApiUnprocessableEntityErrorErrorFromJSON(
  jsonString: string,
): SafeParseResult<MarketApiUnprocessableEntityErrorError, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      MarketApiUnprocessableEntityErrorError$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'MarketApiUnprocessableEntityErrorError' from JSON`,
  );
}
