/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";
import {
  MarketApiV2OrderResponse,
  MarketApiV2OrderResponse$inboundSchema,
} from "./market-api-v2-order-response.js";

export type MarketApiV2ListOrdersResponse = {
  object: "list";
  cursor?: string | undefined;
  hasMore: boolean;
  data: Array<MarketApiV2OrderResponse>;
};

/** @internal */
export const MarketApiV2ListOrdersResponse$inboundSchema: z.ZodMiniType<
  MarketApiV2ListOrdersResponse,
  unknown
> = z.pipe(
  z.object({
    object: z._default(types.literal("list"), "list"),
    cursor: types.optional(types.string()),
    has_more: types.boolean(),
    data: z.array(MarketApiV2OrderResponse$inboundSchema),
  }),
  z.transform((v) => {
    return remap$(v, {
      "has_more": "hasMore",
    });
  }),
);

export function marketApiV2ListOrdersResponseFromJSON(
  jsonString: string,
): SafeParseResult<MarketApiV2ListOrdersResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => MarketApiV2ListOrdersResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'MarketApiV2ListOrdersResponse' from JSON`,
  );
}
