/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../lib/primitives.js";
import {
  MarketApiSchedulerDetailsInputUnion,
  MarketApiSchedulerDetailsInputUnion$Outbound,
  MarketApiSchedulerDetailsInputUnion$outboundSchema,
} from "./market-api-scheduler-details-input-union.js";

export type MarketApiCreateCapacityRequest = {
  name?: string | undefined;
  /**
   * Datacenter locations orders into this capacity can acquire compute from.
   */
  zones: Array<string>;
  /**
   * An ID _or_ name identifying this resource.
   */
  nodeTemplate?: string | undefined;
  /**
   * Automatically start nodes when compute is available. Requires `node_template`.
   */
  startNodesAutomatically: boolean;
  /**
   * Schedulers automatically place buy and sell orders to attempt to achieve desired compute availability.
   */
  scheduler?: MarketApiSchedulerDetailsInputUnion | undefined;
};

/** @internal */
export type MarketApiCreateCapacityRequest$Outbound = {
  name?: string | undefined;
  zones: Array<string>;
  node_template?: string | undefined;
  start_nodes_automatically: boolean;
  scheduler?: MarketApiSchedulerDetailsInputUnion$Outbound | undefined;
};

/** @internal */
export const MarketApiCreateCapacityRequest$outboundSchema: z.ZodMiniType<
  MarketApiCreateCapacityRequest$Outbound,
  MarketApiCreateCapacityRequest
> = z.pipe(
  z.object({
    name: z.optional(z.string()),
    zones: z.array(z.string()),
    nodeTemplate: z.optional(z.string()),
    startNodesAutomatically: z.boolean(),
    scheduler: z.optional(MarketApiSchedulerDetailsInputUnion$outboundSchema),
  }),
  z.transform((v) => {
    return remap$(v, {
      nodeTemplate: "node_template",
      startNodesAutomatically: "start_nodes_automatically",
    });
  }),
);

export function marketApiCreateCapacityRequestToJSON(
  marketApiCreateCapacityRequest: MarketApiCreateCapacityRequest,
): string {
  return JSON.stringify(
    MarketApiCreateCapacityRequest$outboundSchema.parse(
      marketApiCreateCapacityRequest,
    ),
  );
}
