/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import * as openEnums from "../types/enums.js";
import { OpenEnum } from "../types/enums.js";

/**
 * `pending` = not resolved/processed yet.
 *
 * @remarks
 * `filled` = order executed.
 * `standing` = the order is waiting for a match.
 * `cancelled` = the order was cancelled either automatically (not a standing order and didn't immediately fill, or current time past `end_at`) or by explicit cancellation.
 * `rejected` = validation/system error occurred.
 */
export const MarketApiV2OrderStatus = {
  Pending: "pending",
  Filled: "filled",
  Rejected: "rejected",
  Cancelled: "cancelled",
  Standing: "standing",
} as const;
/**
 * `pending` = not resolved/processed yet.
 *
 * @remarks
 * `filled` = order executed.
 * `standing` = the order is waiting for a match.
 * `cancelled` = the order was cancelled either automatically (not a standing order and didn't immediately fill, or current time past `end_at`) or by explicit cancellation.
 * `rejected` = validation/system error occurred.
 */
export type MarketApiV2OrderStatus = OpenEnum<typeof MarketApiV2OrderStatus>;

/** @internal */
export const MarketApiV2OrderStatus$inboundSchema: z.ZodMiniType<
  MarketApiV2OrderStatus,
  unknown
> = openEnums.inboundSchema(MarketApiV2OrderStatus);
/** @internal */
export const MarketApiV2OrderStatus$outboundSchema: z.ZodMiniType<
  string,
  MarketApiV2OrderStatus
> = openEnums.outboundSchema(MarketApiV2OrderStatus);
