/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../lib/primitives.js";

export type MarketApiCreateNodeTemplateRequest = {
  name: string;
  image: string;
  /**
   * Base64-encoded [cloud-init user data](https://cloudinit.readthedocs.io/en/latest/explanation/format/index.html). Maximum 64KB. Currently only the [User-Data Script](https://cloudinit.readthedocs.io/en/latest/explanation/format/user-data-script.html#user-data-script) format is supported.
   */
  cloudInitUserData?: string | undefined;
};

/** @internal */
export type MarketApiCreateNodeTemplateRequest$Outbound = {
  name: string;
  image: string;
  cloud_init_user_data?: string | undefined;
};

/** @internal */
export const MarketApiCreateNodeTemplateRequest$outboundSchema: z.ZodMiniType<
  MarketApiCreateNodeTemplateRequest$Outbound,
  MarketApiCreateNodeTemplateRequest
> = z.pipe(
  z.object({
    name: z.string(),
    image: z.string(),
    cloudInitUserData: z.optional(z.string()),
  }),
  z.transform((v) => {
    return remap$(v, {
      cloudInitUserData: "cloud_init_user_data",
    });
  }),
);

export function marketApiCreateNodeTemplateRequestToJSON(
  marketApiCreateNodeTemplateRequest: MarketApiCreateNodeTemplateRequest,
): string {
  return JSON.stringify(
    MarketApiCreateNodeTemplateRequest$outboundSchema.parse(
      marketApiCreateNodeTemplateRequest,
    ),
  );
}
