/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";
import {
  MarketApiAllocationSchedule,
  MarketApiAllocationSchedule$inboundSchema,
} from "./market-api-allocation-schedule.js";
import {
  MarketApiSchedulerDetails,
  MarketApiSchedulerDetails$inboundSchema,
} from "./market-api-scheduler-details.js";

export type MarketApiCapacityResponse = {
  object: "capacity";
  id: string;
  name?: string | undefined;
  /**
   * Datacenter locations orders into this capacity can acquire compute from.
   */
  zones: Array<string>;
  nodeTemplate?: string | undefined;
  /**
   * If enabled, nodes will be provisioned and terminated + deleted automatically based on currently available allocation in this capacity. Requires `node_template` to be set.
   */
  startNodesAutomatically: boolean;
  allocationSchedule: MarketApiAllocationSchedule;
  /**
   * Unix timestamp.
   */
  createdAt: number;
  /**
   * Schedulers automatically place buy and sell orders to attempt to achieve desired compute availability.
   */
  scheduler?: MarketApiSchedulerDetails | undefined;
};

/** @internal */
export const MarketApiCapacityResponse$inboundSchema: z.ZodMiniType<
  MarketApiCapacityResponse,
  unknown
> = z.pipe(
  z.object({
    object: z._default(types.literal("capacity"), "capacity"),
    id: types.string(),
    name: types.optional(types.string()),
    zones: z.array(types.string()),
    node_template: types.optional(types.string()),
    start_nodes_automatically: types.boolean(),
    allocation_schedule: MarketApiAllocationSchedule$inboundSchema,
    created_at: types.number(),
    scheduler: types.optional(MarketApiSchedulerDetails$inboundSchema),
  }),
  z.transform((v) => {
    return remap$(v, {
      "node_template": "nodeTemplate",
      "start_nodes_automatically": "startNodesAutomatically",
      "allocation_schedule": "allocationSchedule",
      "created_at": "createdAt",
    });
  }),
);

export function marketApiCapacityResponseFromJSON(
  jsonString: string,
): SafeParseResult<MarketApiCapacityResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => MarketApiCapacityResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'MarketApiCapacityResponse' from JSON`,
  );
}
