/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { ClosedEnum } from "../types/enums.js";

export const NodeTemplateInclude = {
  CloudInitUserData: "cloud_init_user_data",
} as const;
export type NodeTemplateInclude = ClosedEnum<typeof NodeTemplateInclude>;

/** @internal */
export const NodeTemplateInclude$outboundSchema: z.ZodMiniEnum<
  typeof NodeTemplateInclude
> = z.enum(NodeTemplateInclude);
