/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";

export type NodeTemplateResponse = {
  object: "node_template";
  id: string;
  name: string;
  image: string;
  /**
   * Whether cloud-init user data is configured for this template.
   */
  cloudInitUserDataUsed: boolean;
  /**
   * Unix timestamp.
   */
  createdAt: number;
  /**
   * Base64-encoded [cloud-init user data](https://cloudinit.readthedocs.io/en/latest/explanation/format/index.html). Currently only the [User-Data Script](https://cloudinit.readthedocs.io/en/latest/explanation/format/user-data-script.html#user-data-script) format is supported.
   */
  cloudInitUserData?: string | undefined;
};

/** @internal */
export const NodeTemplateResponse$inboundSchema: z.ZodMiniType<
  NodeTemplateResponse,
  unknown
> = z.pipe(
  z.object({
    object: z._default(types.literal("node_template"), "node_template"),
    id: types.string(),
    name: types.string(),
    image: types.string(),
    cloud_init_user_data_used: types.boolean(),
    created_at: types.number(),
    cloud_init_user_data: types.optional(types.string()),
  }),
  z.transform((v) => {
    return remap$(v, {
      "cloud_init_user_data_used": "cloudInitUserDataUsed",
      "created_at": "createdAt",
      "cloud_init_user_data": "cloudInitUserData",
    });
  }),
);

export function nodeTemplateResponseFromJSON(
  jsonString: string,
): SafeParseResult<NodeTemplateResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => NodeTemplateResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'NodeTemplateResponse' from JSON`,
  );
}
