/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";
import {
  NodeSshHostKey,
  NodeSshHostKey$inboundSchema,
} from "./node-ssh-host-key.js";

export type NodeSshInfo = {
  hostname: string;
  port: number;
  hostKeys: Array<NodeSshHostKey>;
  /**
   * Unix timestamp.
   */
  lastSuccessfulKeyUpdateAt?: number | undefined;
  /**
   * Unix timestamp.
   */
  lastAttemptedKeyUpdateAt?: number | undefined;
};

/** @internal */
export const NodeSshInfo$inboundSchema: z.ZodMiniType<NodeSshInfo, unknown> = z
  .pipe(
    z.object({
      hostname: types.string(),
      port: types.number(),
      host_keys: z.array(NodeSshHostKey$inboundSchema),
      last_successful_key_update_at: types.optional(types.number()),
      last_attempted_key_update_at: types.optional(types.number()),
    }),
    z.transform((v) => {
      return remap$(v, {
        "host_keys": "hostKeys",
        "last_successful_key_update_at": "lastSuccessfulKeyUpdateAt",
        "last_attempted_key_update_at": "lastAttemptedKeyUpdateAt",
      });
    }),
  );

export function nodeSshInfoFromJSON(
  jsonString: string,
): SafeParseResult<NodeSshInfo, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => NodeSshInfo$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'NodeSshInfo' from JSON`,
  );
}
