/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";

export type NodeLogChunk = {
  /**
   * Unix timestamp.
   */
  timestampRealtime: number;
  /**
   * Monotonic clock seconds.
   */
  timestampMonotonicSecs: number;
  /**
   * Nanosecond component of the monotonic clock.
   */
  timestampMonotonicNanos: number;
  seqnum: number;
  /**
   * Base-64 encoded raw console output.
   */
  data: string;
};

/** @internal */
export const NodeLogChunk$inboundSchema: z.ZodMiniType<NodeLogChunk, unknown> =
  z.pipe(
    z.object({
      timestamp_realtime: types.number(),
      timestamp_monotonic_secs: types.number(),
      timestamp_monotonic_nanos: types.number(),
      seqnum: types.number(),
      data: types.string(),
    }),
    z.transform((v) => {
      return remap$(v, {
        "timestamp_realtime": "timestampRealtime",
        "timestamp_monotonic_secs": "timestampMonotonicSecs",
        "timestamp_monotonic_nanos": "timestampMonotonicNanos",
      });
    }),
  );

export function nodeLogChunkFromJSON(
  jsonString: string,
): SafeParseResult<NodeLogChunk, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => NodeLogChunk$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'NodeLogChunk' from JSON`,
  );
}
