/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../lib/schemas.js";
import { ClosedEnum } from "../types/enums.js";
import { Result as SafeParseResult } from "../types/fp.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";
import { NodeLogChunk, NodeLogChunk$inboundSchema } from "./node-log-chunk.js";

export const NodeLogsResponseObject = {
  List: "list",
} as const;
export type NodeLogsResponseObject = ClosedEnum<typeof NodeLogsResponseObject>;

export type NodeLogsResponse = {
  object: NodeLogsResponseObject;
  data: Array<NodeLogChunk>;
};

/** @internal */
export const NodeLogsResponseObject$inboundSchema: z.ZodMiniEnum<
  typeof NodeLogsResponseObject
> = z.enum(NodeLogsResponseObject);

/** @internal */
export const NodeLogsResponse$inboundSchema: z.ZodMiniType<
  NodeLogsResponse,
  unknown
> = z.object({
  object: NodeLogsResponseObject$inboundSchema,
  data: z.array(NodeLogChunk$inboundSchema),
});

export function nodeLogsResponseFromJSON(
  jsonString: string,
): SafeParseResult<NodeLogsResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => NodeLogsResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'NodeLogsResponse' from JSON`,
  );
}
