/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import { ClosedEnum } from "../types/enums.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";
import { NodeStatus, NodeStatus$inboundSchema } from "./node-status.js";

export const NodeResponseObject = {
  Node: "node",
} as const;
export type NodeResponseObject = ClosedEnum<typeof NodeResponseObject>;

export type NodeResponse = {
  object: NodeResponseObject;
  id: string;
  /**
   * `pending` on creation while waiting for hardware assignment, `running` once assigned (note: the node may still be booting or loading a custom image), `terminated` when destroyed, `failed` on hardware fault.
   */
  status: NodeStatus;
  zone: string;
  capacity: string;
  nodeTemplate: string;
};

/** @internal */
export const NodeResponseObject$inboundSchema: z.ZodMiniEnum<
  typeof NodeResponseObject
> = z.enum(NodeResponseObject);

/** @internal */
export const NodeResponse$inboundSchema: z.ZodMiniType<NodeResponse, unknown> =
  z.pipe(
    z.object({
      object: NodeResponseObject$inboundSchema,
      id: types.string(),
      status: NodeStatus$inboundSchema,
      zone: types.string(),
      capacity: types.string(),
      node_template: types.string(),
    }),
    z.transform((v) => {
      return remap$(v, {
        "node_template": "nodeTemplate",
      });
    }),
  );

export function nodeResponseFromJSON(
  jsonString: string,
): SafeParseResult<NodeResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => NodeResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'NodeResponse' from JSON`,
  );
}
