/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";
import { NodeLogChunk, NodeLogChunk$inboundSchema } from "./node-log-chunk.js";

export type NodeLogsResponse = {
  object: "list";
  data: Array<NodeLogChunk>;
};

/** @internal */
export const NodeLogsResponse$inboundSchema: z.ZodMiniType<
  NodeLogsResponse,
  unknown
> = z.object({
  object: z._default(types.literal("list"), "list"),
  data: z.array(NodeLogChunk$inboundSchema),
});

export function nodeLogsResponseFromJSON(
  jsonString: string,
): SafeParseResult<NodeLogsResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => NodeLogsResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'NodeLogsResponse' from JSON`,
  );
}
