/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { ErrorDetail, ErrorDetail$inboundSchema } from "./error-detail.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";

export type NotFoundErrorError = {
  type: "not_found";
  message: string;
  details?: Array<ErrorDetail> | undefined;
};

/** @internal */
export const NotFoundErrorError$inboundSchema: z.ZodMiniType<
  NotFoundErrorError,
  unknown
> = z.object({
  type: z._default(types.literal("not_found"), "not_found"),
  message: types.string(),
  details: types.optional(z.array(ErrorDetail$inboundSchema)),
});

export function notFoundErrorErrorFromJSON(
  jsonString: string,
): SafeParseResult<NotFoundErrorError, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => NotFoundErrorError$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'NotFoundErrorError' from JSON`,
  );
}
