/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../lib/schemas.js";
import { ClosedEnum } from "../types/enums.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { ErrorDetail, ErrorDetail$inboundSchema } from "./error-detail.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";

export const PaymentRequiredErrorType = {
  PaymentRequired: "payment_required",
} as const;
export type PaymentRequiredErrorType = ClosedEnum<
  typeof PaymentRequiredErrorType
>;

export type PaymentRequiredErrorError = {
  type: PaymentRequiredErrorType;
  message: string;
  details?: Array<ErrorDetail> | undefined;
};

/** @internal */
export const PaymentRequiredErrorType$inboundSchema: z.ZodMiniEnum<
  typeof PaymentRequiredErrorType
> = z.enum(PaymentRequiredErrorType);

/** @internal */
export const PaymentRequiredErrorError$inboundSchema: z.ZodMiniType<
  PaymentRequiredErrorError,
  unknown
> = z.object({
  type: PaymentRequiredErrorType$inboundSchema,
  message: types.string(),
  details: types.optional(z.array(ErrorDetail$inboundSchema)),
});

export function paymentRequiredErrorErrorFromJSON(
  jsonString: string,
): SafeParseResult<PaymentRequiredErrorError, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => PaymentRequiredErrorError$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'PaymentRequiredErrorError' from JSON`,
  );
}
