/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { ErrorDetail, ErrorDetail$inboundSchema } from "./error-detail.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";

export type PaymentRequiredErrorError = {
  type: "payment_required";
  message: string;
  details?: Array<ErrorDetail> | undefined;
};

/** @internal */
export const PaymentRequiredErrorError$inboundSchema: z.ZodMiniType<
  PaymentRequiredErrorError,
  unknown
> = z.object({
  type: z._default(types.literal("payment_required"), "payment_required"),
  message: types.string(),
  details: types.optional(z.array(ErrorDetail$inboundSchema)),
});

export function paymentRequiredErrorErrorFromJSON(
  jsonString: string,
): SafeParseResult<PaymentRequiredErrorError, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => PaymentRequiredErrorError$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'PaymentRequiredErrorError' from JSON`,
  );
}
