/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../lib/primitives.js";

export type ReplaceNodeRequest = {
  /**
   * Node template for the new node. Falls back to capacity default, then original node's template.
   */
  nodeTemplate?: string | null | undefined;
};

/** @internal */
export type ReplaceNodeRequest$Outbound = {
  node_template?: string | null | undefined;
};

/** @internal */
export const ReplaceNodeRequest$outboundSchema: z.ZodMiniType<
  ReplaceNodeRequest$Outbound,
  ReplaceNodeRequest
> = z.pipe(
  z.object({
    nodeTemplate: z.optional(z.nullable(z.string())),
  }),
  z.transform((v) => {
    return remap$(v, {
      nodeTemplate: "node_template",
    });
  }),
);

export function replaceNodeRequestToJSON(
  replaceNodeRequest: ReplaceNodeRequest,
): string {
  return JSON.stringify(
    ReplaceNodeRequest$outboundSchema.parse(replaceNodeRequest),
  );
}
