/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";

export type ScheduleEntry = {
  /**
   * Unix timestamp.
   */
  effectiveAt: number;
  nodeAllocation: number;
};

/** @internal */
export const ScheduleEntry$inboundSchema: z.ZodMiniType<
  ScheduleEntry,
  unknown
> = z.pipe(
  z.object({
    effective_at: types.number(),
    node_allocation: types.number(),
  }),
  z.transform((v) => {
    return remap$(v, {
      "effective_at": "effectiveAt",
      "node_allocation": "nodeAllocation",
    });
  }),
);

export function scheduleEntryFromJSON(
  jsonString: string,
): SafeParseResult<ScheduleEntry, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ScheduleEntry$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ScheduleEntry' from JSON`,
  );
}
