/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import * as openEnums from "../types/enums.js";
import { OpenEnum } from "../types/enums.js";

export const Side = {
  Sell: "sell",
  Buy: "buy",
} as const;
export type Side = OpenEnum<typeof Side>;

/** @internal */
export const Side$inboundSchema: z.ZodMiniType<Side, unknown> = openEnums
  .inboundSchema(Side);
/** @internal */
export const Side$outboundSchema: z.ZodMiniType<string, Side> = openEnums
  .outboundSchema(Side);
