/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";

/**
 * Start a multipart image upload. Max image size is 128 GiB.
 */
export type StartUploadRequest = {
  name: string;
};

/** @internal */
export type StartUploadRequest$Outbound = {
  name: string;
};

/** @internal */
export const StartUploadRequest$outboundSchema: z.ZodMiniType<
  StartUploadRequest$Outbound,
  StartUploadRequest
> = z.object({
  name: z.string(),
});

export function startUploadRequestToJSON(
  startUploadRequest: StartUploadRequest,
): string {
  return JSON.stringify(
    StartUploadRequest$outboundSchema.parse(startUploadRequest),
  );
}
