/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../lib/schemas.js";
import { ClosedEnum } from "../types/enums.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { ErrorDetail, ErrorDetail$inboundSchema } from "./error-detail.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";

export const UnauthorizedErrorType = {
  AuthenticationError: "authentication_error",
} as const;
export type UnauthorizedErrorType = ClosedEnum<typeof UnauthorizedErrorType>;

export type UnauthorizedErrorError = {
  type: UnauthorizedErrorType;
  message: string;
  details?: Array<ErrorDetail> | undefined;
};

/** @internal */
export const UnauthorizedErrorType$inboundSchema: z.ZodMiniEnum<
  typeof UnauthorizedErrorType
> = z.enum(UnauthorizedErrorType);

/** @internal */
export const UnauthorizedErrorError$inboundSchema: z.ZodMiniType<
  UnauthorizedErrorError,
  unknown
> = z.object({
  type: UnauthorizedErrorType$inboundSchema,
  message: types.string(),
  details: types.optional(z.array(ErrorDetail$inboundSchema)),
});

export function unauthorizedErrorErrorFromJSON(
  jsonString: string,
): SafeParseResult<UnauthorizedErrorError, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => UnauthorizedErrorError$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'UnauthorizedErrorError' from JSON`,
  );
}
