/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";

export type UnauthorizedErrorError = {
  type: "authentication_error";
  message: string;
};

/** @internal */
export const UnauthorizedErrorError$inboundSchema: z.ZodMiniType<
  UnauthorizedErrorError,
  unknown
> = z.object({
  type: z._default(
    types.literal("authentication_error"),
    "authentication_error",
  ),
  message: types.string(),
});

export function unauthorizedErrorErrorFromJSON(
  jsonString: string,
): SafeParseResult<UnauthorizedErrorError, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => UnauthorizedErrorError$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'UnauthorizedErrorError' from JSON`,
  );
}
