/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { ErrorDetail, ErrorDetail$inboundSchema } from "./error-detail.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";

export type UnprocessableEntityErrorError = {
  type: "unprocessable_entity";
  message: string;
  details?: Array<ErrorDetail> | undefined;
};

/** @internal */
export const UnprocessableEntityErrorError$inboundSchema: z.ZodMiniType<
  UnprocessableEntityErrorError,
  unknown
> = z.object({
  type: z._default(
    types.literal("unprocessable_entity"),
    "unprocessable_entity",
  ),
  message: types.string(),
  details: types.optional(z.array(ErrorDetail$inboundSchema)),
});

export function unprocessableEntityErrorErrorFromJSON(
  jsonString: string,
): SafeParseResult<UnprocessableEntityErrorError, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => UnprocessableEntityErrorError$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'UnprocessableEntityErrorError' from JSON`,
  );
}
