/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../lib/primitives.js";

export type UploadPartRequest = {
  /**
   * Caller-assigned part number, starting at 1.
   */
  partId: number;
};

/** @internal */
export type UploadPartRequest$Outbound = {
  part_id: number;
};

/** @internal */
export const UploadPartRequest$outboundSchema: z.ZodMiniType<
  UploadPartRequest$Outbound,
  UploadPartRequest
> = z.pipe(
  z.object({
    partId: z.int(),
  }),
  z.transform((v) => {
    return remap$(v, {
      partId: "part_id",
    });
  }),
);

export function uploadPartRequestToJSON(
  uploadPartRequest: UploadPartRequest,
): string {
  return JSON.stringify(
    UploadPartRequest$outboundSchema.parse(uploadPartRequest),
  );
}
