/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../lib/primitives.js";
import { Side, Side$outboundSchema } from "./side.js";

export type V2CreateOrderRequest = {
  /**
   * An ID _or_ name identifying this resource.
   */
  capacity: string;
  side: Side;
  /**
   * If true, the order stays in the order book until either fills, is
   *
   * @remarks
   * explicitly cancelled, or the order end time is reached resulting in
   * automatic cancellation. If false, the order is cancelled immediately if
   * it doesn't fill.
   */
  allowStanding?: boolean | undefined;
  /**
   * Number of nodes to buy or sell between `start_at` and `end_at`.
   */
  nodeCount: number;
  /**
   * Unix timestamp.
   */
  startAt: number;
  /**
   * Unix timestamp.
   */
  endAt: number;
  /**
   * Price rate in dollars per node-hour.
   */
  limitPriceDollarsPerNodeHour: string;
};

/** @internal */
export type V2CreateOrderRequest$Outbound = {
  capacity: string;
  side: string;
  allow_standing?: boolean | undefined;
  node_count: number;
  start_at: number;
  end_at: number;
  limit_price_dollars_per_node_hour: string;
};

/** @internal */
export const V2CreateOrderRequest$outboundSchema: z.ZodMiniType<
  V2CreateOrderRequest$Outbound,
  V2CreateOrderRequest
> = z.pipe(
  z.object({
    capacity: z.string(),
    side: Side$outboundSchema,
    allowStanding: z.optional(z.boolean()),
    nodeCount: z.int(),
    startAt: z.int(),
    endAt: z.int(),
    limitPriceDollarsPerNodeHour: z.string(),
  }),
  z.transform((v) => {
    return remap$(v, {
      allowStanding: "allow_standing",
      nodeCount: "node_count",
      startAt: "start_at",
      endAt: "end_at",
      limitPriceDollarsPerNodeHour: "limit_price_dollars_per_node_hour",
    });
  }),
);

export function v2CreateOrderRequestToJSON(
  v2CreateOrderRequest: V2CreateOrderRequest,
): string {
  return JSON.stringify(
    V2CreateOrderRequest$outboundSchema.parse(v2CreateOrderRequest),
  );
}
