/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import { ClosedEnum } from "../types/enums.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";
import {
  V2OrderResponse,
  V2OrderResponse$inboundSchema,
} from "./v2-order-response.js";

export const V2ListOrdersResponseObject = {
  List: "list",
} as const;
export type V2ListOrdersResponseObject = ClosedEnum<
  typeof V2ListOrdersResponseObject
>;

export type V2ListOrdersResponse = {
  object: V2ListOrdersResponseObject;
  cursor?: string | null | undefined;
  hasMore: boolean;
  data: Array<V2OrderResponse>;
};

/** @internal */
export const V2ListOrdersResponseObject$inboundSchema: z.ZodMiniEnum<
  typeof V2ListOrdersResponseObject
> = z.enum(V2ListOrdersResponseObject);

/** @internal */
export const V2ListOrdersResponse$inboundSchema: z.ZodMiniType<
  V2ListOrdersResponse,
  unknown
> = z.pipe(
  z.object({
    object: V2ListOrdersResponseObject$inboundSchema,
    cursor: z.optional(z.nullable(types.string())),
    has_more: types.boolean(),
    data: z.array(V2OrderResponse$inboundSchema),
  }),
  z.transform((v) => {
    return remap$(v, {
      "has_more": "hasMore",
    });
  }),
);

export function v2ListOrdersResponseFromJSON(
  jsonString: string,
): SafeParseResult<V2ListOrdersResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => V2ListOrdersResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'V2ListOrdersResponse' from JSON`,
  );
}
