/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { ClosedEnum } from "../types/enums.js";

export const V2OrderSortBy = {
  CreatedAt: "created_at",
  MinusCreatedAt: "-created_at",
  StartAt: "start_at",
  MinusStartAt: "-start_at",
} as const;
export type V2OrderSortBy = ClosedEnum<typeof V2OrderSortBy>;

/** @internal */
export const V2OrderSortBy$outboundSchema: z.ZodMiniEnum<typeof V2OrderSortBy> =
  z.enum(V2OrderSortBy);
