/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import * as openEnums from "../types/enums.js";
import { OpenEnum } from "../types/enums.js";

/**
 * `pending` = not resolved/processed yet.
 *
 * @remarks
 *
 * `filled` = order executed.
 *
 * `standing` = the order is waiting for a match.
 *
 * `cancelled` = the order was cancelled either automatically (not a standing
 * order and didn't immediately fill, or current time past `end_at`) or by
 * explicit cancellation.
 *
 * `rejected` = validation/system error occurred.
 */
export const V2OrderStatus = {
  Pending: "pending",
  Filled: "filled",
  Rejected: "rejected",
  Cancelled: "cancelled",
  Standing: "standing",
} as const;
/**
 * `pending` = not resolved/processed yet.
 *
 * @remarks
 *
 * `filled` = order executed.
 *
 * `standing` = the order is waiting for a match.
 *
 * `cancelled` = the order was cancelled either automatically (not a standing
 * order and didn't immediately fill, or current time past `end_at`) or by
 * explicit cancellation.
 *
 * `rejected` = validation/system error occurred.
 */
export type V2OrderStatus = OpenEnum<typeof V2OrderStatus>;

/** @internal */
export const V2OrderStatus$inboundSchema: z.ZodMiniType<
  V2OrderStatus,
  unknown
> = openEnums.inboundSchema(V2OrderStatus);
/** @internal */
export const V2OrderStatus$outboundSchema: z.ZodMiniType<
  string,
  V2OrderStatus
> = openEnums.outboundSchema(V2OrderStatus);
