/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";
import {
  VmorchErrorDetail,
  VmorchErrorDetail$inboundSchema,
} from "./vmorch-error-detail.js";

export type VmorchConflictErrorError = {
  type: "conflict";
  message: string;
  details?: Array<VmorchErrorDetail> | undefined;
};

/** @internal */
export const VmorchConflictErrorError$inboundSchema: z.ZodMiniType<
  VmorchConflictErrorError,
  unknown
> = z.object({
  type: z._default(types.literal("conflict"), "conflict"),
  message: types.string(),
  details: types.optional(z.array(VmorchErrorDetail$inboundSchema)),
});

export function vmorchConflictErrorErrorFromJSON(
  jsonString: string,
): SafeParseResult<VmorchConflictErrorError, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => VmorchConflictErrorError$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'VmorchConflictErrorError' from JSON`,
  );
}
