/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";
import {
  VmorchErrorDetail,
  VmorchErrorDetail$inboundSchema,
} from "./vmorch-error-detail.js";

export type VmorchUnprocessableEntityErrorError = {
  type: "unprocessable_entity";
  message: string;
  details?: Array<VmorchErrorDetail> | undefined;
};

/** @internal */
export const VmorchUnprocessableEntityErrorError$inboundSchema: z.ZodMiniType<
  VmorchUnprocessableEntityErrorError,
  unknown
> = z.object({
  type: z._default(
    types.literal("unprocessable_entity"),
    "unprocessable_entity",
  ),
  message: types.string(),
  details: types.optional(z.array(VmorchErrorDetail$inboundSchema)),
});

export function vmorchUnprocessableEntityErrorErrorFromJSON(
  jsonString: string,
): SafeParseResult<VmorchUnprocessableEntityErrorError, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      VmorchUnprocessableEntityErrorError$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'VmorchUnprocessableEntityErrorError' from JSON`,
  );
}
