/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import * as openEnums from "../types/enums.js";
import { OpenEnum } from "../types/enums.js";

/**
 * Multipart upload status. `started` on creation, `uploading` after first part URL requested, `completed` when finalized, or `failed` on size/checksum/storage error.
 */
export const VmorchImageUploadStatus = {
  Started: "started",
  Uploading: "uploading",
  Completed: "completed",
  Failed: "failed",
} as const;
/**
 * Multipart upload status. `started` on creation, `uploading` after first part URL requested, `completed` when finalized, or `failed` on size/checksum/storage error.
 */
export type VmorchImageUploadStatus = OpenEnum<typeof VmorchImageUploadStatus>;

/** @internal */
export const VmorchImageUploadStatus$inboundSchema: z.ZodMiniType<
  VmorchImageUploadStatus,
  unknown
> = openEnums.inboundSchema(VmorchImageUploadStatus);
