/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";

export type VmorchUploadPartResponse = {
  /**
   * Presigned URL to upload the part.
   */
  url: string;
  /**
   * Unix timestamp.
   */
  expiresAt: number;
};

/** @internal */
export const VmorchUploadPartResponse$inboundSchema: z.ZodMiniType<
  VmorchUploadPartResponse,
  unknown
> = z.pipe(
  z.object({
    url: types.string(),
    expires_at: types.number(),
  }),
  z.transform((v) => {
    return remap$(v, {
      "expires_at": "expiresAt",
    });
  }),
);

export function vmorchUploadPartResponseFromJSON(
  jsonString: string,
): SafeParseResult<VmorchUploadPartResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => VmorchUploadPartResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'VmorchUploadPartResponse' from JSON`,
  );
}
