/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";

export type VmorchNodeSshHostKey = {
  /**
   * Key algorithm.
   */
  keyType: string;
  /**
   * Base64-encoded public key.
   */
  key: string;
};

/** @internal */
export const VmorchNodeSshHostKey$inboundSchema: z.ZodMiniType<
  VmorchNodeSshHostKey,
  unknown
> = z.pipe(
  z.object({
    key_type: types.string(),
    key: types.string(),
  }),
  z.transform((v) => {
    return remap$(v, {
      "key_type": "keyType",
    });
  }),
);

export function vmorchNodeSshHostKeyFromJSON(
  jsonString: string,
): SafeParseResult<VmorchNodeSshHostKey, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => VmorchNodeSshHostKey$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'VmorchNodeSshHostKey' from JSON`,
  );
}
