/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";

/**
 * Complete a multipart image upload.
 */
export type VmorchCompleteUploadRequest = {
  /**
   * Not verified on upload; used during node boot to verify integrity.
   */
  sha256: string;
};

/** @internal */
export type VmorchCompleteUploadRequest$Outbound = {
  sha256: string;
};

/** @internal */
export const VmorchCompleteUploadRequest$outboundSchema: z.ZodMiniType<
  VmorchCompleteUploadRequest$Outbound,
  VmorchCompleteUploadRequest
> = z.object({
  sha256: z.string(),
});

export function vmorchCompleteUploadRequestToJSON(
  vmorchCompleteUploadRequest: VmorchCompleteUploadRequest,
): string {
  return JSON.stringify(
    VmorchCompleteUploadRequest$outboundSchema.parse(
      vmorchCompleteUploadRequest,
    ),
  );
}
