/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../lib/primitives.js";

export type VmorchReplaceNodeRequest = {
  /**
   * Node template for the new node. Falls back to capacity default, then original node's template.
   */
  nodeTemplate?: string | null | undefined;
};

/** @internal */
export type VmorchReplaceNodeRequest$Outbound = {
  node_template?: string | null | undefined;
};

/** @internal */
export const VmorchReplaceNodeRequest$outboundSchema: z.ZodMiniType<
  VmorchReplaceNodeRequest$Outbound,
  VmorchReplaceNodeRequest
> = z.pipe(
  z.object({
    nodeTemplate: z.optional(z.nullable(z.string())),
  }),
  z.transform((v) => {
    return remap$(v, {
      nodeTemplate: "node_template",
    });
  }),
);

export function vmorchReplaceNodeRequestToJSON(
  vmorchReplaceNodeRequest: VmorchReplaceNodeRequest,
): string {
  return JSON.stringify(
    VmorchReplaceNodeRequest$outboundSchema.parse(vmorchReplaceNodeRequest),
  );
}
