/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";

export type VmorchImageDownloadResponse = {
  /**
   * Presigned download URL.
   */
  url: string;
  /**
   * Unix timestamp.
   */
  expiresAt: number;
  /**
   * For integrity verification.
   */
  sha256: string;
  /**
   * Image size in bytes.
   */
  size: number;
};

/** @internal */
export const VmorchImageDownloadResponse$inboundSchema: z.ZodMiniType<
  VmorchImageDownloadResponse,
  unknown
> = z.pipe(
  z.object({
    url: types.string(),
    expires_at: types.number(),
    sha256: types.string(),
    size: types.number(),
  }),
  z.transform((v) => {
    return remap$(v, {
      "expires_at": "expiresAt",
    });
  }),
);

export function vmorchImageDownloadResponseFromJSON(
  jsonString: string,
): SafeParseResult<VmorchImageDownloadResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => VmorchImageDownloadResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'VmorchImageDownloadResponse' from JSON`,
  );
}
