/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";
import {
  VmorchErrorDetail,
  VmorchErrorDetail$inboundSchema,
} from "./vmorch-error-detail.js";

export type VmorchNotFoundErrorError = {
  type: "not_found";
  message: string;
  details?: Array<VmorchErrorDetail> | undefined;
};

/** @internal */
export const VmorchNotFoundErrorError$inboundSchema: z.ZodMiniType<
  VmorchNotFoundErrorError,
  unknown
> = z.object({
  type: z._default(types.literal("not_found"), "not_found"),
  message: types.string(),
  details: types.optional(z.array(VmorchErrorDetail$inboundSchema)),
});

export function vmorchNotFoundErrorErrorFromJSON(
  jsonString: string,
): SafeParseResult<VmorchNotFoundErrorError, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => VmorchNotFoundErrorError$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'VmorchNotFoundErrorError' from JSON`,
  );
}
