/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../lib/primitives.js";

export type VmorchUploadPartRequest = {
  /**
   * Caller-assigned part number, starting at 1.
   */
  partId: number;
};

/** @internal */
export type VmorchUploadPartRequest$Outbound = {
  part_id: number;
};

/** @internal */
export const VmorchUploadPartRequest$outboundSchema: z.ZodMiniType<
  VmorchUploadPartRequest$Outbound,
  VmorchUploadPartRequest
> = z.pipe(
  z.object({
    partId: z.int(),
  }),
  z.transform((v) => {
    return remap$(v, {
      partId: "part_id",
    });
  }),
);

export function vmorchUploadPartRequestToJSON(
  vmorchUploadPartRequest: VmorchUploadPartRequest,
): string {
  return JSON.stringify(
    VmorchUploadPartRequest$outboundSchema.parse(vmorchUploadPartRequest),
  );
}
