/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";
import {
  VmorchImageUploadStatus,
  VmorchImageUploadStatus$inboundSchema,
} from "./vmorch-image-upload-status.js";

export type VmorchImageResponse = {
  object: "image";
  id: string;
  name: string;
  /**
   * Multipart upload status. `started` on creation, `uploading` after first part URL requested, `completed` when finalized, or `failed` on size/checksum/storage error.
   */
  uploadStatus: VmorchImageUploadStatus;
  /**
   * Present when `upload_status` is `completed`. Not verified on upload; used during node boot to verify integrity.
   */
  sha256?: string | null | undefined;
  /**
   * Unix timestamp.
   */
  createdAt: number;
};

/** @internal */
export const VmorchImageResponse$inboundSchema: z.ZodMiniType<
  VmorchImageResponse,
  unknown
> = z.pipe(
  z.object({
    object: z._default(types.literal("image"), "image"),
    id: types.string(),
    name: types.string(),
    upload_status: VmorchImageUploadStatus$inboundSchema,
    sha256: z.optional(z.nullable(types.string())),
    created_at: types.number(),
  }),
  z.transform((v) => {
    return remap$(v, {
      "upload_status": "uploadStatus",
      "created_at": "createdAt",
    });
  }),
);

export function vmorchImageResponseFromJSON(
  jsonString: string,
): SafeParseResult<VmorchImageResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => VmorchImageResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'VmorchImageResponse' from JSON`,
  );
}
