/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";

export type VmorchErrorDetail = {
  /**
   * The field that caused the error (for validation errors)
   */
  field?: string | null | undefined;
  /**
   * Specific error code for this detail
   */
  code: string;
  /**
   * Human-readable error message
   */
  message: string;
};

/** @internal */
export const VmorchErrorDetail$inboundSchema: z.ZodMiniType<
  VmorchErrorDetail,
  unknown
> = z.object({
  field: z.optional(z.nullable(types.string())),
  code: types.string(),
  message: types.string(),
});

export function vmorchErrorDetailFromJSON(
  jsonString: string,
): SafeParseResult<VmorchErrorDetail, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => VmorchErrorDetail$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'VmorchErrorDetail' from JSON`,
  );
}
