/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";
import {
  VmorchErrorDetail,
  VmorchErrorDetail$inboundSchema,
} from "./vmorch-error-detail.js";

export type VmorchInternalServerErrorError = {
  type: "api_error";
  message: string;
  details?: Array<VmorchErrorDetail> | undefined;
};

/** @internal */
export const VmorchInternalServerErrorError$inboundSchema: z.ZodMiniType<
  VmorchInternalServerErrorError,
  unknown
> = z.object({
  type: z._default(types.literal("api_error"), "api_error"),
  message: types.string(),
  details: types.optional(z.array(VmorchErrorDetail$inboundSchema)),
});

export function vmorchInternalServerErrorErrorFromJSON(
  jsonString: string,
): SafeParseResult<VmorchInternalServerErrorError, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => VmorchInternalServerErrorError$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'VmorchInternalServerErrorError' from JSON`,
  );
}
