/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";
import {
  VmorchNodeLogChunk,
  VmorchNodeLogChunk$inboundSchema,
} from "./vmorch-node-log-chunk.js";

export type VmorchNodeLogsResponse = {
  object: "list";
  data: Array<VmorchNodeLogChunk>;
};

/** @internal */
export const VmorchNodeLogsResponse$inboundSchema: z.ZodMiniType<
  VmorchNodeLogsResponse,
  unknown
> = z.object({
  object: z._default(types.literal("list"), "list"),
  data: z.array(VmorchNodeLogChunk$inboundSchema),
});

export function vmorchNodeLogsResponseFromJSON(
  jsonString: string,
): SafeParseResult<VmorchNodeLogsResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => VmorchNodeLogsResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'VmorchNodeLogsResponse' from JSON`,
  );
}
