/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";
import {
  VmorchNodeSshHostKey,
  VmorchNodeSshHostKey$inboundSchema,
} from "./vmorch-node-ssh-host-key.js";

export type VmorchNodeSshInfo = {
  hostname: string;
  port: number;
  hostKeys: Array<VmorchNodeSshHostKey>;
  /**
   * Unix timestamp.
   */
  lastSuccessfulKeyUpdateAt?: number | undefined;
  /**
   * Unix timestamp.
   */
  lastAttemptedKeyUpdateAt?: number | undefined;
};

/** @internal */
export const VmorchNodeSshInfo$inboundSchema: z.ZodMiniType<
  VmorchNodeSshInfo,
  unknown
> = z.pipe(
  z.object({
    hostname: types.string(),
    port: types.number(),
    host_keys: z.array(VmorchNodeSshHostKey$inboundSchema),
    last_successful_key_update_at: types.optional(types.number()),
    last_attempted_key_update_at: types.optional(types.number()),
  }),
  z.transform((v) => {
    return remap$(v, {
      "host_keys": "hostKeys",
      "last_successful_key_update_at": "lastSuccessfulKeyUpdateAt",
      "last_attempted_key_update_at": "lastAttemptedKeyUpdateAt",
    });
  }),
);

export function vmorchNodeSshInfoFromJSON(
  jsonString: string,
): SafeParseResult<VmorchNodeSshInfo, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => VmorchNodeSshInfo$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'VmorchNodeSshInfo' from JSON`,
  );
}
