/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";
import {
  VmorchImageResponse,
  VmorchImageResponse$inboundSchema,
} from "./vmorch-image-response.js";

export type VmorchListImagesResponse = {
  object: "list";
  cursor?: string | undefined;
  hasMore: boolean;
  data: Array<VmorchImageResponse>;
};

/** @internal */
export const VmorchListImagesResponse$inboundSchema: z.ZodMiniType<
  VmorchListImagesResponse,
  unknown
> = z.pipe(
  z.object({
    object: z._default(types.literal("list"), "list"),
    cursor: types.optional(types.string()),
    has_more: types.boolean(),
    data: z.array(VmorchImageResponse$inboundSchema),
  }),
  z.transform((v) => {
    return remap$(v, {
      "has_more": "hasMore",
    });
  }),
);

export function vmorchListImagesResponseFromJSON(
  jsonString: string,
): SafeParseResult<VmorchListImagesResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => VmorchListImagesResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'VmorchListImagesResponse' from JSON`,
  );
}
