/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";
import {
  VmorchNodeStatus,
  VmorchNodeStatus$inboundSchema,
} from "./vmorch-node-status.js";

export type VmorchNodeResponse = {
  object: "node";
  id: string;
  /**
   * `pending` on creation while waiting for hardware assignment, `running` once assigned (note: the node may still be booting or loading a custom image), `terminated` when destroyed, `failed` on hardware fault.
   */
  status: VmorchNodeStatus;
  zone: string;
  capacity: string;
  nodeTemplate: string;
};

/** @internal */
export const VmorchNodeResponse$inboundSchema: z.ZodMiniType<
  VmorchNodeResponse,
  unknown
> = z.pipe(
  z.object({
    object: z._default(types.literal("node"), "node"),
    id: types.string(),
    status: VmorchNodeStatus$inboundSchema,
    zone: types.string(),
    capacity: types.string(),
    node_template: types.string(),
  }),
  z.transform((v) => {
    return remap$(v, {
      "node_template": "nodeTemplate",
    });
  }),
);

export function vmorchNodeResponseFromJSON(
  jsonString: string,
): SafeParseResult<VmorchNodeResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => VmorchNodeResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'VmorchNodeResponse' from JSON`,
  );
}
