/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import * as openEnums from "../types/enums.js";
import { OpenEnum } from "../types/enums.js";

/**
 * `pending` on creation while waiting for hardware assignment, `running` once assigned (note: the node may still be booting or loading a custom image), `terminated` when destroyed, `failed` on hardware fault.
 */
export const VmorchNodeStatus = {
  Pending: "pending",
  Running: "running",
  Terminated: "terminated",
  Failed: "failed",
} as const;
/**
 * `pending` on creation while waiting for hardware assignment, `running` once assigned (note: the node may still be booting or loading a custom image), `terminated` when destroyed, `failed` on hardware fault.
 */
export type VmorchNodeStatus = OpenEnum<typeof VmorchNodeStatus>;

/** @internal */
export const VmorchNodeStatus$inboundSchema: z.ZodMiniType<
  VmorchNodeStatus,
  unknown
> = openEnums.inboundSchema(VmorchNodeStatus);
/** @internal */
export const VmorchNodeStatus$outboundSchema: z.ZodMiniType<
  string,
  VmorchNodeStatus
> = openEnums.outboundSchema(VmorchNodeStatus);
