/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";

/**
 * Start a multipart image upload. Max image size is 128 GiB.
 */
export type VmorchStartUploadRequest = {
  name: string;
};

/** @internal */
export type VmorchStartUploadRequest$Outbound = {
  name: string;
};

/** @internal */
export const VmorchStartUploadRequest$outboundSchema: z.ZodMiniType<
  VmorchStartUploadRequest$Outbound,
  VmorchStartUploadRequest
> = z.object({
  name: z.string(),
});

export function vmorchStartUploadRequestToJSON(
  vmorchStartUploadRequest: VmorchStartUploadRequest,
): string {
  return JSON.stringify(
    VmorchStartUploadRequest$outboundSchema.parse(vmorchStartUploadRequest),
  );
}
