/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";
import {
  VmorchErrorDetail,
  VmorchErrorDetail$inboundSchema,
} from "./vmorch-error-detail.js";

export type VmorchUnauthorizedErrorError = {
  type: "authentication_error";
  message: string;
  details?: Array<VmorchErrorDetail> | undefined;
};

/** @internal */
export const VmorchUnauthorizedErrorError$inboundSchema: z.ZodMiniType<
  VmorchUnauthorizedErrorError,
  unknown
> = z.object({
  type: z._default(
    types.literal("authentication_error"),
    "authentication_error",
  ),
  message: types.string(),
  details: types.optional(z.array(VmorchErrorDetail$inboundSchema)),
});

export function vmorchUnauthorizedErrorErrorFromJSON(
  jsonString: string,
): SafeParseResult<VmorchUnauthorizedErrorError, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => VmorchUnauthorizedErrorError$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'VmorchUnauthorizedErrorError' from JSON`,
  );
}
